// Mocks generated by Mockito 5.4.6 from annotations
// in gloria_marketing_flutter/test/auth_validation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:gloria_marketing_flutter/src/core/services/data_sync_service.dart'
    as _i9;
import 'package:gloria_marketing_flutter/src/core/services/shared_preferences_service.dart'
    as _i31;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/akb_by_category.dart'
    as _i23;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region.dart'
    as _i4;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region_report.dart'
    as _i22;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/client_contract.dart'
    as _i17;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/kpi_data.dart'
    as _i3;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/main_report.dart'
    as _i21;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/order.dart'
    as _i28;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/order_detail.dart'
    as _i5;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/order_status.dart'
    as _i27;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/planned_route.dart'
    as _i30;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/price_type.dart'
    as _i13;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_balance.dart'
    as _i18;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_brand.dart'
    as _i19;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_data.dart'
    as _i12;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_price.dart'
    as _i14;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_series.dart'
    as _i20;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_with_price.dart'
    as _i26;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/sales_req_permissions.dart'
    as _i29;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/trading_point.dart'
    as _i11;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/user_warehouse.dart'
    as _i15;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan.dart'
    as _i24;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan_list.dart'
    as _i25;
import 'package:gloria_marketing_flutter/src/features/agent/presentation/widgets/data_sync_progress_widget.dart'
    as _i10;
import 'package:gloria_marketing_flutter/src/features/auth/domain/entities/user_entity.dart'
    as _i2;
import 'package:gloria_marketing_flutter/src/features/auth/domain/repositories/auth_repository.dart'
    as _i7;
import 'package:gloria_marketing_flutter/src/features/marketing/data/models/promotion_model.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i32;
import 'package:shared_preferences/shared_preferences.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKpiData_1 extends _i1.SmartFake implements _i3.KpiData {
  _FakeKpiData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBusinessRegion_2 extends _i1.SmartFake
    implements _i4.BusinessRegion {
  _FakeBusinessRegion_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetail_3 extends _i1.SmartFake implements _i5.OrderDetail {
  _FakeOrderDetail_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_4 extends _i1.SmartFake
    implements _i6.SharedPreferences {
  _FakeSharedPreferences_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.UserEntity> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i8.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.UserEntity>);
}

/// A class which mocks [DataSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSyncService extends _i1.Mock implements _i9.DataSyncService {
  MockDataSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> registerBackgroundSync({
    Duration? frequency = const Duration(hours: 6),
    String? userCode,
    String? password,
    String? codeProject,
    String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerBackgroundSync, [], {
              #frequency: frequency,
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> cancelBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#cancelBackgroundSync, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> registerRetrySync({
    required Map<String, dynamic>? failedOperation,
    Duration? delay = const Duration(minutes: 15),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerRetrySync, [], {
              #failedOperation: failedOperation,
              #delay: delay,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> validateUserWithDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#validateUserWithDatabase, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> syncUserDataWithDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#syncUserDataWithDatabase, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCachedData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCachedData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearMainReportData() =>
      (super.noSuchMethod(
            Invocation.method(#clearMainReportData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> syncAllUserData({
    required String? userCode,
    required String? password,
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllUserData, [], {
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<_i10.SyncStep> syncAllUserDataWithProgress({
    required String? userCode,
    required String? password,
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllUserDataWithProgress, [], {
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i8.Stream<_i10.SyncStep>.empty(),
          )
          as _i8.Stream<_i10.SyncStep>);

  @override
  _i8.Future<_i3.KpiData> syncKpiData({
    required String? userCode,
    required String? password,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncKpiData, [], {
              #userCode: userCode,
              #password: password,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<_i3.KpiData>.value(
              _FakeKpiData_1(
                this,
                Invocation.method(#syncKpiData, [], {
                  #userCode: userCode,
                  #password: password,
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.KpiData>);

  @override
  _i8.Future<List<_i11.TradingPoint>> syncClients({
    required String? userCode,
    required String? password,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncClients, [], {
              #userCode: userCode,
              #password: password,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i11.TradingPoint>>.value(
              <_i11.TradingPoint>[],
            ),
          )
          as _i8.Future<List<_i11.TradingPoint>>);

  @override
  _i8.Future<List<_i12.ProductData>> syncProducts({
    required String? codeProject,
    required String? codeSklad,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncProducts, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i12.ProductData>>.value(
              <_i12.ProductData>[],
            ),
          )
          as _i8.Future<List<_i12.ProductData>>);

  @override
  _i8.Future<List<_i13.PriceType>> syncPriceTypes({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncPriceTypes, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i13.PriceType>>.value(
              <_i13.PriceType>[],
            ),
          )
          as _i8.Future<List<_i13.PriceType>>);

  @override
  _i8.Future<List<_i14.ProductPrice>> syncProductPrices({
    required String? userCode,
    bool? forceRefresh = false,
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncProductPrices, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i8.Future<List<_i14.ProductPrice>>.value(
              <_i14.ProductPrice>[],
            ),
          )
          as _i8.Future<List<_i14.ProductPrice>>);

  @override
  _i8.Future<List<_i4.BusinessRegion>> syncBusinessRegions({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncBusinessRegions, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i4.BusinessRegion>>.value(
              <_i4.BusinessRegion>[],
            ),
          )
          as _i8.Future<List<_i4.BusinessRegion>>);

  @override
  _i8.Future<List<_i15.UserWarehouse>> syncUserWarehouses({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserWarehouses, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i15.UserWarehouse>>.value(
              <_i15.UserWarehouse>[],
            ),
          )
          as _i8.Future<List<_i15.UserWarehouse>>);

  @override
  _i8.Future<Map<String, dynamic>> syncProductBalances({
    required String? codeProject,
    required String? codeSklad,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncProductBalances, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i4.BusinessRegion> createBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i8.Future<_i4.BusinessRegion>.value(
              _FakeBusinessRegion_2(
                this,
                Invocation.method(#createBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.BusinessRegion>);

  @override
  _i8.Future<_i4.BusinessRegion> updateBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i8.Future<_i4.BusinessRegion>.value(
              _FakeBusinessRegion_2(
                this,
                Invocation.method(#updateBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.BusinessRegion>);

  @override
  _i8.Future<void> deleteBusinessRegion({
    required String? userCode,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAllBusinessRegions({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBusinessRegions, [], {
              #userCode: userCode,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i16.PromotionModel>> syncPromotions({
    String? authToken,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncPromotions, [], {
              #authToken: authToken,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i16.PromotionModel>>.value(
              <_i16.PromotionModel>[],
            ),
          )
          as _i8.Future<List<_i16.PromotionModel>>);

  @override
  _i8.Future<List<_i17.ClientContract>> syncClientContracts({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncClientContracts, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i17.ClientContract>>.value(
              <_i17.ClientContract>[],
            ),
          )
          as _i8.Future<List<_i17.ClientContract>>);

  @override
  _i8.Future<void> updateClientsHasContractField() =>
      (super.noSuchMethod(
            Invocation.method(#updateClientsHasContractField, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> syncReportByPeriod({
    required String? userCode,
    required String? dateStart,
    required String? dateEnd,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncReportByPeriod, [], {
              #userCode: userCode,
              #dateStart: dateStart,
              #dateEnd: dateEnd,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i3.KpiData?> getCachedKpiData(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedKpiData, [userCode]),
            returnValue: _i8.Future<_i3.KpiData?>.value(),
          )
          as _i8.Future<_i3.KpiData?>);

  @override
  _i8.Future<List<_i11.TradingPoint>> getCachedClients() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedClients, []),
            returnValue: _i8.Future<List<_i11.TradingPoint>>.value(
              <_i11.TradingPoint>[],
            ),
          )
          as _i8.Future<List<_i11.TradingPoint>>);

  @override
  _i8.Future<List<_i12.ProductData>> getCachedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProducts, []),
            returnValue: _i8.Future<List<_i12.ProductData>>.value(
              <_i12.ProductData>[],
            ),
          )
          as _i8.Future<List<_i12.ProductData>>);

  @override
  _i8.Future<List<_i13.PriceType>> getCachedPriceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPriceTypes, []),
            returnValue: _i8.Future<List<_i13.PriceType>>.value(
              <_i13.PriceType>[],
            ),
          )
          as _i8.Future<List<_i13.PriceType>>);

  @override
  _i8.Future<List<_i14.ProductPrice>> getCachedProductPrices({
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductPrices, [], {
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i8.Future<List<_i14.ProductPrice>>.value(
              <_i14.ProductPrice>[],
            ),
          )
          as _i8.Future<List<_i14.ProductPrice>>);

  @override
  _i8.Future<List<_i4.BusinessRegion>> getCachedBusinessRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBusinessRegions, []),
            returnValue: _i8.Future<List<_i4.BusinessRegion>>.value(
              <_i4.BusinessRegion>[],
            ),
          )
          as _i8.Future<List<_i4.BusinessRegion>>);

  @override
  _i8.Future<List<_i15.UserWarehouse>> getCachedUserWarehouses() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUserWarehouses, []),
            returnValue: _i8.Future<List<_i15.UserWarehouse>>.value(
              <_i15.UserWarehouse>[],
            ),
          )
          as _i8.Future<List<_i15.UserWarehouse>>);

  @override
  _i8.Future<List<_i18.ProductBalance>> getCachedProductBalances({
    String? warehouseCode,
    String? productBrand,
    String? productSeries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductBalances, [], {
              #warehouseCode: warehouseCode,
              #productBrand: productBrand,
              #productSeries: productSeries,
            }),
            returnValue: _i8.Future<List<_i18.ProductBalance>>.value(
              <_i18.ProductBalance>[],
            ),
          )
          as _i8.Future<List<_i18.ProductBalance>>);

  @override
  _i8.Future<List<_i19.ProductBrand>> getCachedProductBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductBrands, []),
            returnValue: _i8.Future<List<_i19.ProductBrand>>.value(
              <_i19.ProductBrand>[],
            ),
          )
          as _i8.Future<List<_i19.ProductBrand>>);

  @override
  _i8.Future<List<_i20.ProductSeries>> getCachedProductSeries({
    String? brandName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductSeries, [], {
              #brandName: brandName,
            }),
            returnValue: _i8.Future<List<_i20.ProductSeries>>.value(
              <_i20.ProductSeries>[],
            ),
          )
          as _i8.Future<List<_i20.ProductSeries>>);

  @override
  _i8.Future<List<_i17.ClientContract>> getCachedClientContracts({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedClientContracts, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i8.Future<List<_i17.ClientContract>>.value(
              <_i17.ClientContract>[],
            ),
          )
          as _i8.Future<List<_i17.ClientContract>>);

  @override
  _i8.Future<List<_i17.ClientContractWithName>>
  getCachedClientContractsWithNames({String? clientCode, bool? active}) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedClientContractsWithNames, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i8.Future<List<_i17.ClientContractWithName>>.value(
              <_i17.ClientContractWithName>[],
            ),
          )
          as _i8.Future<List<_i17.ClientContractWithName>>);

  @override
  _i8.Future<List<_i16.PromotionModel>> getCachedPromotions({
    bool? onlyActive = true,
    String? searchQuery,
    DateTime? dateFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPromotions, [], {
              #onlyActive: onlyActive,
              #searchQuery: searchQuery,
              #dateFilter: dateFilter,
            }),
            returnValue: _i8.Future<List<_i16.PromotionModel>>.value(
              <_i16.PromotionModel>[],
            ),
          )
          as _i8.Future<List<_i16.PromotionModel>>);

  @override
  _i8.Future<List<_i21.MainReport>> getCachedMainReports({String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMainReports, [], {#userCode: userCode}),
            returnValue: _i8.Future<List<_i21.MainReport>>.value(
              <_i21.MainReport>[],
            ),
          )
          as _i8.Future<List<_i21.MainReport>>);

  @override
  _i8.Future<List<_i22.BusinessRegionReport>> getCachedBusinessRegionReports({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBusinessRegionReports, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i8.Future<List<_i22.BusinessRegionReport>>.value(
              <_i22.BusinessRegionReport>[],
            ),
          )
          as _i8.Future<List<_i22.BusinessRegionReport>>);

  @override
  _i8.Future<List<_i23.AKBByCategory>> getCachedAKBByCategories({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAKBByCategories, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i8.Future<List<_i23.AKBByCategory>>.value(
              <_i23.AKBByCategory>[],
            ),
          )
          as _i8.Future<List<_i23.AKBByCategory>>);

  @override
  _i8.Future<List<_i24.VisitPlan>> getCachedVisitPlans({
    int? mainReportId,
    String? clientCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVisitPlans, [], {
              #mainReportId: mainReportId,
              #clientCode: clientCode,
            }),
            returnValue: _i8.Future<List<_i24.VisitPlan>>.value(
              <_i24.VisitPlan>[],
            ),
          )
          as _i8.Future<List<_i24.VisitPlan>>);

  @override
  _i8.Future<List<_i25.VisitPlanList>> getCachedVisitPlanLists({
    int? visitPlanId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVisitPlanLists, [], {
              #visitPlanId: visitPlanId,
            }),
            returnValue: _i8.Future<List<_i25.VisitPlanList>>.value(
              <_i25.VisitPlanList>[],
            ),
          )
          as _i8.Future<List<_i25.VisitPlanList>>);

  @override
  _i8.Future<List<_i26.ProductWithPrice>> getCachedProductsWithPrices({
    required String? priceTypeCode,
    List<String>? warehouseCodes,
    String? searchQuery,
    String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductsWithPrices, [], {
              #priceTypeCode: priceTypeCode,
              #warehouseCodes: warehouseCodes,
              #searchQuery: searchQuery,
              #codeProject: codeProject,
            }),
            returnValue: _i8.Future<List<_i26.ProductWithPrice>>.value(
              <_i26.ProductWithPrice>[],
            ),
          )
          as _i8.Future<List<_i26.ProductWithPrice>>);

  @override
  _i8.Future<void> updateCachedClients(List<_i11.TradingPoint>? clients) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedClients, [clients]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resolveConflicts({
    required String? dataType,
    required List<Map<String, dynamic>>? localData,
    required List<Map<String, dynamic>>? remoteData,
    _i9.ConflictResolutionStrategy? strategy =
        _i9.ConflictResolutionStrategy.lastWriteWins,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflicts, [], {
              #dataType: dataType,
              #localData: localData,
              #remoteData: remoteData,
              #strategy: strategy,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> retryFailedOperations() =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedOperations, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isEvyapServerSelected() =>
      (super.noSuchMethod(
            Invocation.method(#isEvyapServerSelected, []),
            returnValue: false,
          )
          as bool);

  @override
  bool isAvonServerSelected() =>
      (super.noSuchMethod(
            Invocation.method(#isAvonServerSelected, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<List<_i27.OrderStatus>> syncOrderStatuses({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncOrderStatuses, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i27.OrderStatus>>.value(
              <_i27.OrderStatus>[],
            ),
          )
          as _i8.Future<List<_i27.OrderStatus>>);

  @override
  _i8.Future<List<_i28.Order>> syncOrders({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncOrders, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i28.Order>>.value(<_i28.Order>[]),
          )
          as _i8.Future<List<_i28.Order>>);

  @override
  _i8.Future<List<_i27.OrderStatus>> getCachedOrderStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrderStatuses, []),
            returnValue: _i8.Future<List<_i27.OrderStatus>>.value(
              <_i27.OrderStatus>[],
            ),
          )
          as _i8.Future<List<_i27.OrderStatus>>);

  @override
  _i8.Future<List<_i28.Order>> getCachedOrders({
    String? clientCode,
    String? mainStatus,
    String? typePriceCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrders, [], {
              #clientCode: clientCode,
              #mainStatus: mainStatus,
              #typePriceCode: typePriceCode,
            }),
            returnValue: _i8.Future<List<_i28.Order>>.value(<_i28.Order>[]),
          )
          as _i8.Future<List<_i28.Order>>);

  @override
  _i8.Future<_i28.Order?> getCachedOrderByNumOrder(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrderByNumOrder, [numOrder]),
            returnValue: _i8.Future<_i28.Order?>.value(),
          )
          as _i8.Future<_i28.Order?>);

  @override
  _i8.Future<void> updateCachedOrderStatus(
    String? numOrder,
    String? mainStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedOrderStatus, [numOrder, mainStatus]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCachedOrder(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCachedOrder, [numOrder]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getCachedCourierNames() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedCourierNames, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> getCachedCourierCars() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedCourierCars, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<_i5.OrderDetail> syncOrderDetails({
    required String? numberOrder,
    required String? orderDate1,
    required String? orderDate2,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncOrderDetails, [], {
              #numberOrder: numberOrder,
              #orderDate1: orderDate1,
              #orderDate2: orderDate2,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<_i5.OrderDetail>.value(
              _FakeOrderDetail_3(
                this,
                Invocation.method(#syncOrderDetails, [], {
                  #numberOrder: numberOrder,
                  #orderDate1: orderDate1,
                  #orderDate2: orderDate2,
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.OrderDetail>);

  @override
  _i8.Future<List<_i5.OrderDetail>> getCachedOrderDetails({String? numOrder}) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrderDetails, [], {
              #numOrder: numOrder,
            }),
            returnValue: _i8.Future<List<_i5.OrderDetail>>.value(
              <_i5.OrderDetail>[],
            ),
          )
          as _i8.Future<List<_i5.OrderDetail>>);

  @override
  _i8.Future<_i5.OrderDetail?> getCachedOrderDetailByNumOrder(
    String? numOrder,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOrderDetailByNumOrder, [numOrder]),
            returnValue: _i8.Future<_i5.OrderDetail?>.value(),
          )
          as _i8.Future<_i5.OrderDetail?>);

  @override
  _i8.Future<void> saveCachedOrderDetail(_i5.OrderDetail? orderDetail) =>
      (super.noSuchMethod(
            Invocation.method(#saveCachedOrderDetail, [orderDetail]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateCachedOrderDetail(
    String? numOrder,
    _i5.OrderDetail? orderDetail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedOrderDetail, [
              numOrder,
              orderDetail,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCachedOrderDetail(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCachedOrderDetail, [numOrder]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i29.SalesReqPermissions?> syncSalesReqPermissions({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncSalesReqPermissions, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<_i29.SalesReqPermissions?>.value(),
          )
          as _i8.Future<_i29.SalesReqPermissions?>);

  @override
  _i8.Future<_i29.SalesReqPermissions?> getCachedSalesReqPermissions(
    String? userCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSalesReqPermissions, [userCode]),
            returnValue: _i8.Future<_i29.SalesReqPermissions?>.value(),
          )
          as _i8.Future<_i29.SalesReqPermissions?>);

  @override
  _i8.Future<List<_i30.PlannedRoute>> syncPlannedRoutes({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncPlannedRoutes, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i8.Future<List<_i30.PlannedRoute>>.value(
              <_i30.PlannedRoute>[],
            ),
          )
          as _i8.Future<List<_i30.PlannedRoute>>);

  @override
  _i8.Future<List<_i30.PlannedRoute>> getCachedPlannedRoutes(
    String? userCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPlannedRoutes, [userCode]),
            returnValue: _i8.Future<List<_i30.PlannedRoute>>.value(
              <_i30.PlannedRoute>[],
            ),
          )
          as _i8.Future<List<_i30.PlannedRoute>>);

  @override
  _i8.Future<List<_i30.PlannedRoute>> getCachedPlannedRoutesByWeekday(
    String? userCode,
    int? codeWeekday,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPlannedRoutesByWeekday, [
              userCode,
              codeWeekday,
            ]),
            returnValue: _i8.Future<List<_i30.PlannedRoute>>.value(
              <_i30.PlannedRoute>[],
            ),
          )
          as _i8.Future<List<_i30.PlannedRoute>>);

  @override
  _i8.Future<List<_i30.PlannedRoute>> getCachedPlannedRoutesByClient(
    String? userCode,
    String? codeClient,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPlannedRoutesByClient, [
              userCode,
              codeClient,
            ]),
            returnValue: _i8.Future<List<_i30.PlannedRoute>>.value(
              <_i30.PlannedRoute>[],
            ),
          )
          as _i8.Future<List<_i30.PlannedRoute>>);

  @override
  _i8.Future<Map<String, String>> syncMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#syncMapTokens, []),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  Map<String, String> getCachedMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMapTokens, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool hasValidMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidMapTokens, []),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i31.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.SharedPreferences get preferences =>
      (super.noSuchMethod(
            Invocation.getter(#preferences),
            returnValue: _FakeSharedPreferences_4(
              this,
              Invocation.getter(#preferences),
            ),
          )
          as _i6.SharedPreferences);

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveCredentials(
    String? username,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [
              username,
              password,
              rememberMe,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveUserData({
    required String? userCode,
    required String? userName,
    required String? warehouseCode,
    required String? codeProject,
    required String? telegramID,
    required String? chatID,
    required String? topicID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userCode: userCode,
              #userName: userName,
              #warehouseCode: warehouseCode,
              #codeProject: codeProject,
              #telegramID: telegramID,
              #chatID: chatID,
              #topicID: topicID,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isRememberMeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isRememberMeEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> setServerName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setServerName, [name]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> clearServerName() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerName, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> setBaseUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setBaseUrl, [url]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> clearBaseUrl() =>
      (super.noSuchMethod(
            Invocation.method(#clearBaseUrl, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setOfflineMode(bool? isOffline) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineMode, [isOffline]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#isOfflineMode, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<void> clearOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#clearOfflineMode, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String getLanguageCode() =>
      (super.noSuchMethod(
            Invocation.method(#getLanguageCode, []),
            returnValue: _i32.dummyValue<String>(
              this,
              Invocation.method(#getLanguageCode, []),
            ),
          )
          as String);

  @override
  _i8.Future<void> clearLanguageCode() =>
      (super.noSuchMethod(
            Invocation.method(#clearLanguageCode, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setReportSentToTelegram(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setReportSentToTelegram, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  bool isReportSentToTelegram() =>
      (super.noSuchMethod(
            Invocation.method(#isReportSentToTelegram, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<bool> saveMapTokens({
    required String? yandexToken,
    required String? googleToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMapTokens, [], {
              #yandexToken: yandexToken,
              #googleToken: googleToken,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  Map<String, String> getMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getMapTokens, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool hasValidMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidMapTokens, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<bool> clearMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearMapTokens, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
