// Mocks generated by Mockito 5.4.6 from annotations
// in gloria_marketing_flutter/test/business_region_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:gloria_marketing_flutter/src/core/database/database_helper.dart'
    as _i40;
import 'package:gloria_marketing_flutter/src/core/services/api_database_service.dart'
    as _i24;
import 'package:gloria_marketing_flutter/src/core/services/shared_preferences_service.dart'
    as _i6;
import 'package:gloria_marketing_flutter/src/core/services/soap_api_service.dart'
    as _i9;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/akb_by_category.dart'
    as _i32;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region.dart'
    as _i11;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region_report.dart'
    as _i31;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/client_contract.dart'
    as _i17;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/contract_type.dart'
    as _i22;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/create_order.dart'
    as _i19;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/district_contracting.dart'
    as _i23;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/kpi_data.dart'
    as _i3;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/main_report.dart'
    as _i30;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/order.dart'
    as _i20;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/order_detail.dart'
    as _i4;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/order_status.dart'
    as _i18;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/planned_route.dart'
    as _i37;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/price_type.dart'
    as _i14;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_balance.dart'
    as _i27;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_brand.dart'
    as _i25;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_data.dart'
    as _i13;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_image.dart'
    as _i39;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_price.dart'
    as _i15;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_series.dart'
    as _i26;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_with_price.dart'
    as _i29;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/sales_req_permissions.dart'
    as _i35;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/thumbnail.dart'
    as _i38;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/trading_point.dart'
    as _i10;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/trading_point_with_permissions.dart'
    as _i28;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/user_organization.dart'
    as _i21;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/user_warehouse.dart'
    as _i12;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_data.dart'
    as _i36;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan.dart'
    as _i33;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan_list.dart'
    as _i34;
import 'package:gloria_marketing_flutter/src/features/marketing/data/models/promotion_model.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:sqflite/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKpiData_1 extends _i1.SmartFake implements _i3.KpiData {
  _FakeKpiData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDetail_2 extends _i1.SmartFake implements _i4.OrderDetail {
  _FakeOrderDetail_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_3 extends _i1.SmartFake implements _i5.Database {
  _FakeDatabase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i6.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get preferences =>
      (super.noSuchMethod(
            Invocation.getter(#preferences),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#preferences),
            ),
          )
          as _i2.SharedPreferences);

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveCredentials(
    String? username,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [
              username,
              password,
              rememberMe,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserData({
    required String? userCode,
    required String? userName,
    required String? warehouseCode,
    required String? codeProject,
    required String? telegramID,
    required String? chatID,
    required String? topicID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userCode: userCode,
              #userName: userName,
              #warehouseCode: warehouseCode,
              #codeProject: codeProject,
              #telegramID: telegramID,
              #chatID: chatID,
              #topicID: topicID,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool isRememberMeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isRememberMeEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> setServerName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setServerName, [name]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clearServerName() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerName, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setBaseUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setBaseUrl, [url]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clearBaseUrl() =>
      (super.noSuchMethod(
            Invocation.method(#clearBaseUrl, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setOfflineMode(bool? isOffline) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineMode, [isOffline]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool isOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#isOfflineMode, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> clearOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#clearOfflineMode, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  String getLanguageCode() =>
      (super.noSuchMethod(
            Invocation.method(#getLanguageCode, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getLanguageCode, []),
            ),
          )
          as String);

  @override
  _i7.Future<void> clearLanguageCode() =>
      (super.noSuchMethod(
            Invocation.method(#clearLanguageCode, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setReportSentToTelegram(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setReportSentToTelegram, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool isReportSentToTelegram() =>
      (super.noSuchMethod(
            Invocation.method(#isReportSentToTelegram, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<bool> saveMapTokens({
    required String? yandexToken,
    required String? googleToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveMapTokens, [], {
              #yandexToken: yandexToken,
              #googleToken: googleToken,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  Map<String, String> getMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getMapTokens, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool hasValidMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#hasValidMapTokens, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<bool> clearMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearMapTokens, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setBgSyncEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBgSyncEnabled, [enabled]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool isBgSyncEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBgSyncEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> setBgSyncInterval(int? hours) =>
      (super.noSuchMethod(
            Invocation.method(#setBgSyncInterval, [hours]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  int getBgSyncInterval() =>
      (super.noSuchMethod(
            Invocation.method(#getBgSyncInterval, []),
            returnValue: 0,
          )
          as int);

  @override
  _i7.Future<void> setBgSyncCustomMinutes(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setBgSyncCustomMinutes, [minutes]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SoapApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoapApiService extends _i1.Mock implements _i9.SoapApiService {
  MockSoapApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.KpiData> getKpiData({
    required String? userCode,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [], {
              #userCode: userCode,
              #password: password,
            }),
            returnValue: _i7.Future<_i3.KpiData>.value(
              _FakeKpiData_1(
                this,
                Invocation.method(#getKpiData, [], {
                  #userCode: userCode,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.KpiData>);

  @override
  _i7.Future<List<_i10.TradingPoint>> getClients({
    required String? userCode,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClients, [], {
              #userCode: userCode,
              #password: password,
            }),
            returnValue: _i7.Future<List<_i10.TradingPoint>>.value(
              <_i10.TradingPoint>[],
            ),
          )
          as _i7.Future<List<_i10.TradingPoint>>);

  @override
  _i7.Future<List<_i11.BusinessRegion>> getBusinessRegions({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegions, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i11.BusinessRegion>>.value(
              <_i11.BusinessRegion>[],
            ),
          )
          as _i7.Future<List<_i11.BusinessRegion>>);

  @override
  _i7.Future<List<_i12.UserWarehouse>> getWarehousesUser({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWarehousesUser, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i12.UserWarehouse>>.value(
              <_i12.UserWarehouse>[],
            ),
          )
          as _i7.Future<List<_i12.UserWarehouse>>);

  @override
  _i7.Future<String> createBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> updateBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#updateBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> deleteBusinessRegion({
    required String? userCode,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
            }),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deleteBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> deleteAllBusinessRegions({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBusinessRegions, [], {
              #userCode: userCode,
            }),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deleteAllBusinessRegions, [], {
                  #userCode: userCode,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<_i13.ProductData>> getProducts({
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i7.Future<List<_i13.ProductData>>.value(
              <_i13.ProductData>[],
            ),
          )
          as _i7.Future<List<_i13.ProductData>>);

  @override
  _i7.Future<Map<String, dynamic>> getProductBalances({
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalances, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i14.PriceType>> getPriceTypes({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i14.PriceType>>.value(
              <_i14.PriceType>[],
            ),
          )
          as _i7.Future<List<_i14.PriceType>>);

  @override
  _i7.Future<List<_i15.ProductPrice>> getProductPrices({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i15.ProductPrice>>.value(
              <_i15.ProductPrice>[],
            ),
          )
          as _i7.Future<List<_i15.ProductPrice>>);

  @override
  _i7.Future<List<_i16.PromotionModel>> getPromotions({String? authToken}) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotions, [], {#authToken: authToken}),
            returnValue: _i7.Future<List<_i16.PromotionModel>>.value(
              <_i16.PromotionModel>[],
            ),
          )
          as _i7.Future<List<_i16.PromotionModel>>);

  @override
  _i7.Future<List<_i17.ClientContract>> getAllContracts({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllContracts, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i17.ClientContract>>.value(
              <_i17.ClientContract>[],
            ),
          )
          as _i7.Future<List<_i17.ClientContract>>);

  @override
  _i7.Future<Map<String, dynamic>> getReportByPeriod({
    required String? userCode,
    required String? dateStart,
    required String? dateEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReportByPeriod, [], {
              #userCode: userCode,
              #dateStart: dateStart,
              #dateEnd: dateEnd,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i18.OrderStatus>> getOrderStatusList({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusList, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i18.OrderStatus>>.value(
              <_i18.OrderStatus>[],
            ),
          )
          as _i7.Future<List<_i18.OrderStatus>>);

  @override
  String generateSetOrderSoapRequest(_i19.CreateOrder? order) =>
      (super.noSuchMethod(
            Invocation.method(#generateSetOrderSoapRequest, [order]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateSetOrderSoapRequest, [order]),
            ),
          )
          as String);

  @override
  _i7.Future<List<_i20.Order>> getOrderList({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderList, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i20.Order>>.value(<_i20.Order>[]),
          )
          as _i7.Future<List<_i20.Order>>);

  @override
  _i7.Future<Map<String, dynamic>> getSalesReqPermissions({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesReqPermissions, [], {
              #userCode: userCode,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getPlannedRouteList({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedRouteList, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, String>> getMapTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getMapTokens, []),
            returnValue: _i7.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<String> updateClientCoordinates({
    required String? userCode,
    required String? clientCode,
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientCoordinates, [], {
              #userCode: userCode,
              #clientCode: clientCode,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#updateClientCoordinates, [], {
                  #userCode: userCode,
                  #clientCode: clientCode,
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i4.OrderDetail> getOrderDetails({
    required String? numberOrder,
    required String? orderDate1,
    required String? orderDate2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetails, [], {
              #numberOrder: numberOrder,
              #orderDate1: orderDate1,
              #orderDate2: orderDate2,
            }),
            returnValue: _i7.Future<_i4.OrderDetail>.value(
              _FakeOrderDetail_2(
                this,
                Invocation.method(#getOrderDetails, [], {
                  #numberOrder: numberOrder,
                  #orderDate1: orderDate1,
                  #orderDate2: orderDate2,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.OrderDetail>);

  @override
  _i7.Future<Map<String, dynamic>> setOrder({
    required _i19.CreateOrder? order,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setOrder, [], {#order: order}),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i21.UserOrganization>> getOrganizationsByUserCode({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrganizationsByUserCode, [], {
              #userCode: userCode,
            }),
            returnValue: _i7.Future<List<_i21.UserOrganization>>.value(
              <_i21.UserOrganization>[],
            ),
          )
          as _i7.Future<List<_i21.UserOrganization>>);

  @override
  _i7.Future<Map<String, dynamic>> checkAccessOnStartup({
    required String? userId,
    required String? localUuid,
    String? appDeviceId,
    required String? platform,
    required String? brand,
    required String? model,
    required String? osVersion,
    String? sdk,
    required String? appVersion,
    String? deviceFingerprint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkAccessOnStartup, [], {
              #userId: userId,
              #localUuid: localUuid,
              #appDeviceId: appDeviceId,
              #platform: platform,
              #brand: brand,
              #model: model,
              #osVersion: osVersion,
              #sdk: sdk,
              #appVersion: appVersion,
              #deviceFingerprint: deviceFingerprint,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i22.ContractType>> getTypeOfContract() =>
      (super.noSuchMethod(
            Invocation.method(#getTypeOfContract, []),
            returnValue: _i7.Future<List<_i22.ContractType>>.value(
              <_i22.ContractType>[],
            ),
          )
          as _i7.Future<List<_i22.ContractType>>);

  @override
  _i7.Future<List<_i23.DistrictContracting>> getCitiesDistrictContracting({
    required String? codeUser,
    required String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCitiesDistrictContracting, [], {
              #codeUser: codeUser,
              #codeProject: codeProject,
            }),
            returnValue: _i7.Future<List<_i23.DistrictContracting>>.value(
              <_i23.DistrictContracting>[],
            ),
          )
          as _i7.Future<List<_i23.DistrictContracting>>);

  @override
  _i7.Future<Map<String, dynamic>> setContract({
    required String? dateOfContract,
    required String? codeUser,
    required String? codeClient,
    required double? sumOfContract,
    String? termReference,
    String? termCertificate,
    String? numbReference,
    String? numbCertificate,
    required String? typeOfContract,
    String? numbPassport,
    String? termPassport,
    bool? certificateUnlimited = false,
    String? psCodeProject,
    String? psCodeDistrict,
    String? psNameDistrict,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setContract, [], {
              #dateOfContract: dateOfContract,
              #codeUser: codeUser,
              #codeClient: codeClient,
              #sumOfContract: sumOfContract,
              #termReference: termReference,
              #termCertificate: termCertificate,
              #numbReference: numbReference,
              #numbCertificate: numbCertificate,
              #typeOfContract: typeOfContract,
              #numbPassport: numbPassport,
              #termPassport: termPassport,
              #certificateUnlimited: certificateUnlimited,
              #psCodeProject: psCodeProject,
              #psCodeDistrict: psCodeDistrict,
              #psNameDistrict: psNameDistrict,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> setClient({
    required String? name,
    required String? signboard,
    required String? inn,
    required String? tradePointType,
    required String? contactPerson,
    required String? contactPersonPhone,
    required String? address,
    required String? addressDelivery,
    required String? referencePoint,
    required String? responsiblePersonPhone,
    required double? longitude,
    required double? latitude,
    required String? codeUser,
    required String? codeRegion,
    String? director,
    String? mfo,
    String? bankAccount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setClient, [], {
              #name: name,
              #signboard: signboard,
              #inn: inn,
              #tradePointType: tradePointType,
              #contactPerson: contactPerson,
              #contactPersonPhone: contactPersonPhone,
              #address: address,
              #addressDelivery: addressDelivery,
              #referencePoint: referencePoint,
              #responsiblePersonPhone: responsiblePersonPhone,
              #longitude: longitude,
              #latitude: latitude,
              #codeUser: codeUser,
              #codeRegion: codeRegion,
              #director: director,
              #mfo: mfo,
              #bankAccount: bankAccount,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [ApiDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiDatabaseService extends _i1.Mock
    implements _i24.ApiDatabaseService {
  MockApiDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i5.Database>.value(
              _FakeDatabase_3(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i5.Database>);

  @override
  _i7.Future<void> saveKpiData(String? userCode, _i3.KpiData? kpiData) =>
      (super.noSuchMethod(
            Invocation.method(#saveKpiData, [userCode, kpiData]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.KpiData?> getKpiData(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [userCode]),
            returnValue: _i7.Future<_i3.KpiData?>.value(),
          )
          as _i7.Future<_i3.KpiData?>);

  @override
  _i7.Future<void> saveClients(List<_i10.TradingPoint>? clients) =>
      (super.noSuchMethod(
            Invocation.method(#saveClients, [clients]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.TradingPoint>> getClients() =>
      (super.noSuchMethod(
            Invocation.method(#getClients, []),
            returnValue: _i7.Future<List<_i10.TradingPoint>>.value(
              <_i10.TradingPoint>[],
            ),
          )
          as _i7.Future<List<_i10.TradingPoint>>);

  @override
  _i7.Future<List<String>> getUniqueTradePointTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueTradePointTypes, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> saveProducts(List<_i13.ProductData>? products) =>
      (super.noSuchMethod(
            Invocation.method(#saveProducts, [products]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i13.ProductData>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i7.Future<List<_i13.ProductData>>.value(
              <_i13.ProductData>[],
            ),
          )
          as _i7.Future<List<_i13.ProductData>>);

  @override
  _i7.Future<_i13.ProductData?> getProductByCode(String? productCode) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByCode, [productCode]),
            returnValue: _i7.Future<_i13.ProductData?>.value(),
          )
          as _i7.Future<_i13.ProductData?>);

  @override
  _i7.Future<void> savePriceTypes(List<_i14.PriceType>? priceTypes) =>
      (super.noSuchMethod(
            Invocation.method(#savePriceTypes, [priceTypes]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i14.PriceType>> getPriceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, []),
            returnValue: _i7.Future<List<_i14.PriceType>>.value(
              <_i14.PriceType>[],
            ),
          )
          as _i7.Future<List<_i14.PriceType>>);

  @override
  _i7.Future<void> saveProductPrices(List<_i15.ProductPrice>? productPrices) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductPrices, [productPrices]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i15.ProductPrice>> getProductPrices({
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i7.Future<List<_i15.ProductPrice>>.value(
              <_i15.ProductPrice>[],
            ),
          )
          as _i7.Future<List<_i15.ProductPrice>>);

  @override
  _i7.Future<void> savePromotions(List<_i16.PromotionModel>? promotions) =>
      (super.noSuchMethod(
            Invocation.method(#savePromotions, [promotions]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i16.PromotionModel>> getPromotions({
    bool? onlyActive = true,
    String? searchQuery,
    DateTime? dateFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotions, [], {
              #onlyActive: onlyActive,
              #searchQuery: searchQuery,
              #dateFilter: dateFilter,
            }),
            returnValue: _i7.Future<List<_i16.PromotionModel>>.value(
              <_i16.PromotionModel>[],
            ),
          )
          as _i7.Future<List<_i16.PromotionModel>>);

  @override
  _i7.Future<_i16.PromotionModel?> getPromotionByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotionByCode, [code]),
            returnValue: _i7.Future<_i16.PromotionModel?>.value(),
          )
          as _i7.Future<_i16.PromotionModel?>);

  @override
  _i7.Future<void> updatePromotionSyncTime(String? code, DateTime? syncTime) =>
      (super.noSuchMethod(
            Invocation.method(#updatePromotionSyncTime, [code, syncTime]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deletePromotion(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deletePromotion, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> getPromotionCount({bool? onlyActive = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotionCount, [], {
              #onlyActive: onlyActive,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> saveBusinessRegions(List<_i11.BusinessRegion>? regions) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegions, [regions]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.BusinessRegion>> getBusinessRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegions, []),
            returnValue: _i7.Future<List<_i11.BusinessRegion>>.value(
              <_i11.BusinessRegion>[],
            ),
          )
          as _i7.Future<List<_i11.BusinessRegion>>);

  @override
  _i7.Future<_i11.BusinessRegion?> getBusinessRegionByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegionByCode, [code]),
            returnValue: _i7.Future<_i11.BusinessRegion?>.value(),
          )
          as _i7.Future<_i11.BusinessRegion?>);

  @override
  _i7.Future<void> saveBusinessRegion(_i11.BusinessRegion? region) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegion, [region]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateBusinessRegion(
    String? code,
    _i11.BusinessRegion? region,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [code, region]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteBusinessRegion(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserWarehouses(List<_i12.UserWarehouse>? warehouses) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserWarehouses, [warehouses]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i12.UserWarehouse>> getUserWarehouses() =>
      (super.noSuchMethod(
            Invocation.method(#getUserWarehouses, []),
            returnValue: _i7.Future<List<_i12.UserWarehouse>>.value(
              <_i12.UserWarehouse>[],
            ),
          )
          as _i7.Future<List<_i12.UserWarehouse>>);

  @override
  _i7.Future<_i12.UserWarehouse?> getUserWarehouseByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWarehouseByCode, [code]),
            returnValue: _i7.Future<_i12.UserWarehouse?>.value(),
          )
          as _i7.Future<_i12.UserWarehouse?>);

  @override
  _i7.Future<void> saveUserWarehouse(_i12.UserWarehouse? warehouse) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserWarehouse, [warehouse]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserWarehouse(
    String? code,
    _i12.UserWarehouse? warehouse,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserWarehouse, [code, warehouse]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteUserWarehouse(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserWarehouse, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveProductBrands(List<_i25.ProductBrand>? brands) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBrands, [brands]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i25.ProductBrand>> getProductBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getProductBrands, []),
            returnValue: _i7.Future<List<_i25.ProductBrand>>.value(
              <_i25.ProductBrand>[],
            ),
          )
          as _i7.Future<List<_i25.ProductBrand>>);

  @override
  _i7.Future<_i25.ProductBrand?> getProductBrandByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBrandByName, [name]),
            returnValue: _i7.Future<_i25.ProductBrand?>.value(),
          )
          as _i7.Future<_i25.ProductBrand?>);

  @override
  _i7.Future<void> saveProductBrand(_i25.ProductBrand? brand) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBrand, [brand]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProductBrand(String? name, _i25.ProductBrand? brand) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductBrand, [name, brand]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProductBrand(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductBrand, [name]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveProductSeries(List<_i26.ProductSeries>? series) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductSeries, [series]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i26.ProductSeries>> getProductSeries({String? brandName}) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSeries, [], {#brandName: brandName}),
            returnValue: _i7.Future<List<_i26.ProductSeries>>.value(
              <_i26.ProductSeries>[],
            ),
          )
          as _i7.Future<List<_i26.ProductSeries>>);

  @override
  _i7.Future<_i26.ProductSeries?> getProductSeriesByNameAndBrand(
    String? name,
    String? brandName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSeriesByNameAndBrand, [
              name,
              brandName,
            ]),
            returnValue: _i7.Future<_i26.ProductSeries?>.value(),
          )
          as _i7.Future<_i26.ProductSeries?>);

  @override
  _i7.Future<void> saveProductSerie(_i26.ProductSeries? series) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductSerie, [series]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProductSeries(
    String? name,
    String? brandName,
    _i26.ProductSeries? series,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductSeries, [name, brandName, series]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProductSeries(String? name, String? brandName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductSeries, [name, brandName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveProductBalances(List<_i27.ProductBalance>? balances) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBalances, [balances]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i27.ProductBalance>> getProductBalances({
    String? warehouseCode,
    String? productBrand,
    String? productSeries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalances, [], {
              #warehouseCode: warehouseCode,
              #productBrand: productBrand,
              #productSeries: productSeries,
            }),
            returnValue: _i7.Future<List<_i27.ProductBalance>>.value(
              <_i27.ProductBalance>[],
            ),
          )
          as _i7.Future<List<_i27.ProductBalance>>);

  @override
  _i7.Future<_i27.ProductBalance?> getProductBalanceByCodes(
    String? warehouseCode,
    String? productCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalanceByCodes, [
              warehouseCode,
              productCode,
            ]),
            returnValue: _i7.Future<_i27.ProductBalance?>.value(),
          )
          as _i7.Future<_i27.ProductBalance?>);

  @override
  _i7.Future<void> saveProductBalance(_i27.ProductBalance? balance) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBalance, [balance]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProductBalance(
    String? warehouseCode,
    String? productCode,
    _i27.ProductBalance? balance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductBalance, [
              warehouseCode,
              productCode,
              balance,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProductBalance(
    String? warehouseCode,
    String? productCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductBalance, [
              warehouseCode,
              productCode,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i28.TradingPointWithPermissions>>
  getTradingPointsWithPermissions(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getTradingPointsWithPermissions, [userCode]),
            returnValue:
                _i7.Future<List<_i28.TradingPointWithPermissions>>.value(
                  <_i28.TradingPointWithPermissions>[],
                ),
          )
          as _i7.Future<List<_i28.TradingPointWithPermissions>>);

  @override
  _i7.Future<List<_i29.ProductWithPrice>> getProductsWithPrices({
    required String? priceTypeCode,
    List<String>? warehouseCodes,
    String? searchQuery,
    String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsWithPrices, [], {
              #priceTypeCode: priceTypeCode,
              #warehouseCodes: warehouseCodes,
              #searchQuery: searchQuery,
              #codeProject: codeProject,
            }),
            returnValue: _i7.Future<List<_i29.ProductWithPrice>>.value(
              <_i29.ProductWithPrice>[],
            ),
          )
          as _i7.Future<List<_i29.ProductWithPrice>>);

  @override
  _i7.Future<void> saveClientContracts(List<_i17.ClientContract>? contracts) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientContracts, [contracts]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i17.ClientContract>> getClientContracts({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContracts, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i7.Future<List<_i17.ClientContract>>.value(
              <_i17.ClientContract>[],
            ),
          )
          as _i7.Future<List<_i17.ClientContract>>);

  @override
  _i7.Future<List<_i17.ClientContractWithName>> getClientContractsWithNames({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContractsWithNames, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i7.Future<List<_i17.ClientContractWithName>>.value(
              <_i17.ClientContractWithName>[],
            ),
          )
          as _i7.Future<List<_i17.ClientContractWithName>>);

  @override
  _i7.Future<_i17.ClientContract?> getClientContractByCode(
    String? codeContract,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContractByCode, [codeContract]),
            returnValue: _i7.Future<_i17.ClientContract?>.value(),
          )
          as _i7.Future<_i17.ClientContract?>);

  @override
  _i7.Future<void> saveClientContract(_i17.ClientContract? contract) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientContract, [contract]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateClientContract(
    String? codeContract,
    _i17.ClientContract? contract,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientContract, [codeContract, contract]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteClientContract(String? codeContract) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClientContract, [codeContract]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveMainReports(List<_i30.MainReport>? reports) =>
      (super.noSuchMethod(
            Invocation.method(#saveMainReports, [reports]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i30.MainReport>> getMainReports({String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getMainReports, [], {#userCode: userCode}),
            returnValue: _i7.Future<List<_i30.MainReport>>.value(
              <_i30.MainReport>[],
            ),
          )
          as _i7.Future<List<_i30.MainReport>>);

  @override
  _i7.Future<_i30.MainReport?> getMainReportById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMainReportById, [id]),
            returnValue: _i7.Future<_i30.MainReport?>.value(),
          )
          as _i7.Future<_i30.MainReport?>);

  @override
  _i7.Future<void> saveBusinessRegionReports(
    List<_i31.BusinessRegionReport>? reports,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegionReports, [reports]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i31.BusinessRegionReport>> getBusinessRegionReports({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegionReports, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i7.Future<List<_i31.BusinessRegionReport>>.value(
              <_i31.BusinessRegionReport>[],
            ),
          )
          as _i7.Future<List<_i31.BusinessRegionReport>>);

  @override
  _i7.Future<void> saveAKBByCategories(List<_i32.AKBByCategory>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#saveAKBByCategories, [categories]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i32.AKBByCategory>> getAKBByCategories({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAKBByCategories, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i7.Future<List<_i32.AKBByCategory>>.value(
              <_i32.AKBByCategory>[],
            ),
          )
          as _i7.Future<List<_i32.AKBByCategory>>);

  @override
  _i7.Future<void> saveVisitPlans(List<_i33.VisitPlan>? plans) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitPlans, [plans]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i33.VisitPlan>> getVisitPlans({
    int? mainReportId,
    String? clientCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitPlans, [], {
              #mainReportId: mainReportId,
              #clientCode: clientCode,
            }),
            returnValue: _i7.Future<List<_i33.VisitPlan>>.value(
              <_i33.VisitPlan>[],
            ),
          )
          as _i7.Future<List<_i33.VisitPlan>>);

  @override
  _i7.Future<void> saveVisitPlanLists(List<_i34.VisitPlanList>? lists) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitPlanLists, [lists]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i34.VisitPlanList>> getVisitPlanLists({int? visitPlanId}) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitPlanLists, [], {
              #visitPlanId: visitPlanId,
            }),
            returnValue: _i7.Future<List<_i34.VisitPlanList>>.value(
              <_i34.VisitPlanList>[],
            ),
          )
          as _i7.Future<List<_i34.VisitPlanList>>);

  @override
  _i7.Future<void> saveMainReportsByDelete(List<_i30.MainReport>? reports) =>
      (super.noSuchMethod(
            Invocation.method(#saveMainReportsByDelete, [reports]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearMainReport() =>
      (super.noSuchMethod(
            Invocation.method(#clearMainReport, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveOrderStatuses(List<_i18.OrderStatus>? statuses) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrderStatuses, [statuses]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i18.OrderStatus>> getOrderStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatuses, []),
            returnValue: _i7.Future<List<_i18.OrderStatus>>.value(
              <_i18.OrderStatus>[],
            ),
          )
          as _i7.Future<List<_i18.OrderStatus>>);

  @override
  _i7.Future<_i18.OrderStatus?> getOrderStatusByMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderStatusByMessage, [message]),
            returnValue: _i7.Future<_i18.OrderStatus?>.value(),
          )
          as _i7.Future<_i18.OrderStatus?>);

  @override
  _i7.Future<void> saveCourier(String? name, String? car) =>
      (super.noSuchMethod(
            Invocation.method(#saveCourier, [name, car]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveCourierCar(String? car) =>
      (super.noSuchMethod(
            Invocation.method(#saveCourierCar, [car]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<String>> getUniqueCourierNames() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueCourierNames, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<String>> getUniqueCourierCars() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueCourierCars, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> saveOrders(List<_i20.Order>? orders) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrders, [orders]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i20.Order>> getOrders({
    String? clientCode,
    String? mainStatus,
    String? typePriceCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {
              #clientCode: clientCode,
              #mainStatus: mainStatus,
              #typePriceCode: typePriceCode,
            }),
            returnValue: _i7.Future<List<_i20.Order>>.value(<_i20.Order>[]),
          )
          as _i7.Future<List<_i20.Order>>);

  @override
  _i7.Future<_i20.Order?> getOrderByNumOrder(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderByNumOrder, [numOrder]),
            returnValue: _i7.Future<_i20.Order?>.value(),
          )
          as _i7.Future<_i20.Order?>);

  @override
  _i7.Future<void> updateOrderStatus(String? numOrder, String? mainStatus) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [numOrder, mainStatus]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteOrder(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [numOrder]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveOrderDetails(List<_i4.OrderDetail>? orderDetails) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrderDetails, [orderDetails]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.OrderDetail>> getOrderDetails({String? numOrder}) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetails, [], {#numOrder: numOrder}),
            returnValue: _i7.Future<List<_i4.OrderDetail>>.value(
              <_i4.OrderDetail>[],
            ),
          )
          as _i7.Future<List<_i4.OrderDetail>>);

  @override
  _i7.Future<_i4.OrderDetail?> getOrderDetailByNumOrder(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderDetailByNumOrder, [numOrder]),
            returnValue: _i7.Future<_i4.OrderDetail?>.value(),
          )
          as _i7.Future<_i4.OrderDetail?>);

  @override
  _i7.Future<void> saveOrderDetail(
    _i4.OrderDetail? orderDetail, {
    bool? validateOrderExists = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveOrderDetail,
              [orderDetail],
              {#validateOrderExists: validateOrderExists},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateOrderDetail(
    String? numOrder,
    _i4.OrderDetail? orderDetail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderDetail, [numOrder, orderDetail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteOrderDetail(String? numOrder) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrderDetail, [numOrder]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveSalesReqPermissions(
    List<_i35.SalesReqPermissions>? permissions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSalesReqPermissions, [permissions]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i35.SalesReqPermissions?> getSalesReqPermissions(
    String? userCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSalesReqPermissions, [userCode]),
            returnValue: _i7.Future<_i35.SalesReqPermissions?>.value(),
          )
          as _i7.Future<_i35.SalesReqPermissions?>);

  @override
  _i7.Future<List<_i35.SalesReqPermissions>> getAllSalesReqPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSalesReqPermissions, []),
            returnValue: _i7.Future<List<_i35.SalesReqPermissions>>.value(
              <_i35.SalesReqPermissions>[],
            ),
          )
          as _i7.Future<List<_i35.SalesReqPermissions>>);

  @override
  _i7.Future<void> saveVisitStepsLegacy(List<_i35.VisitStep>? visitSteps) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitStepsLegacy, [visitSteps]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSalesReqPermissions(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSalesReqPermissions, [userCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearSalesReqPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#clearSalesReqPermissions, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveVisitSteps(
    List<_i35.VisitStep>? visitSteps,
    int? salesReqPermissionsId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitSteps, [
              visitSteps,
              salesReqPermissionsId,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i35.VisitStep>> getVisitSteps(int? salesReqPermissionsId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitSteps, [salesReqPermissionsId]),
            returnValue: _i7.Future<List<_i35.VisitStep>>.value(
              <_i35.VisitStep>[],
            ),
          )
          as _i7.Future<List<_i35.VisitStep>>);

  @override
  _i7.Future<_i35.VisitStep?> getVisitStepById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitStepById, [id]),
            returnValue: _i7.Future<_i35.VisitStep?>.value(),
          )
          as _i7.Future<_i35.VisitStep?>);

  @override
  _i7.Future<void> updateVisitStep(int? id, _i35.VisitStep? visitStep) =>
      (super.noSuchMethod(
            Invocation.method(#updateVisitStep, [id, visitStep]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVisitStep(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisitStep, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVisitStepsByPermissionsId(
    int? salesReqPermissionsId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisitStepsByPermissionsId, [
              salesReqPermissionsId,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i35.VisitStep>> getAllVisitSteps() =>
      (super.noSuchMethod(
            Invocation.method(#getAllVisitSteps, []),
            returnValue: _i7.Future<List<_i35.VisitStep>>.value(
              <_i35.VisitStep>[],
            ),
          )
          as _i7.Future<List<_i35.VisitStep>>);

  @override
  _i7.Future<int> getVisitStepsCount(int? salesReqPermissionsId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitStepsCount, [salesReqPermissionsId]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> saveVisitStepData(_i36.VisitData? visitData) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitStepData, [visitData]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveVisitStepDataBatch(
    List<_i36.VisitData>? visitDataList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitStepDataBatch, [visitDataList]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i36.VisitData>> getVisitStepDataByVisitId(String? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitStepDataByVisitId, [visitId]),
            returnValue: _i7.Future<List<_i36.VisitData>>.value(
              <_i36.VisitData>[],
            ),
          )
          as _i7.Future<List<_i36.VisitData>>);

  @override
  _i7.Future<List<_i36.VisitData>> getVisitStepDataByUser(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitStepDataByUser, [userCode]),
            returnValue: _i7.Future<List<_i36.VisitData>>.value(
              <_i36.VisitData>[],
            ),
          )
          as _i7.Future<List<_i36.VisitData>>);

  @override
  _i7.Future<List<_i36.VisitData>> getVisitStepDataByClient(
    String? clientCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitStepDataByClient, [clientCode]),
            returnValue: _i7.Future<List<_i36.VisitData>>.value(
              <_i36.VisitData>[],
            ),
          )
          as _i7.Future<List<_i36.VisitData>>);

  @override
  _i7.Future<List<_i36.VisitData>> getPendingSyncVisitStepData() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncVisitStepData, []),
            returnValue: _i7.Future<List<_i36.VisitData>>.value(
              <_i36.VisitData>[],
            ),
          )
          as _i7.Future<List<_i36.VisitData>>);

  @override
  _i7.Future<void> updateVisitStepDataSyncStatus(
    int? id,
    bool? isSynced, {
    String? syncError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateVisitStepDataSyncStatus,
              [id, isSynced],
              {#syncError: syncError},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getVisitStepDataStats() =>
      (super.noSuchMethod(
            Invocation.method(#getVisitStepDataStats, []),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> deleteOldVisitStepData({
    Duration? olderThan = const Duration(days: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldVisitStepData, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVisitStepDataByVisitId(String? visitId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisitStepDataByVisitId, [visitId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVisitStepDataByClient(String? clientCode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisitStepDataByClient, [clientCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVisitStepDataByStepCode(
    String? visitId,
    int? stepCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisitStepDataByStepCode, [
              visitId,
              stepCode,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteVisitStepData(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVisitStepData, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> savePlannedRoutes(List<_i37.PlannedRoute>? routes) =>
      (super.noSuchMethod(
            Invocation.method(#savePlannedRoutes, [routes]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i37.PlannedRoute>> getPlannedRoutes(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedRoutes, [userCode]),
            returnValue: _i7.Future<List<_i37.PlannedRoute>>.value(
              <_i37.PlannedRoute>[],
            ),
          )
          as _i7.Future<List<_i37.PlannedRoute>>);

  @override
  _i7.Future<List<_i37.PlannedRoute>> getAllPlannedRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlannedRoutes, []),
            returnValue: _i7.Future<List<_i37.PlannedRoute>>.value(
              <_i37.PlannedRoute>[],
            ),
          )
          as _i7.Future<List<_i37.PlannedRoute>>);

  @override
  _i7.Future<List<_i37.PlannedRoute>> getPlannedRoutesByWeekday(
    String? userCode,
    int? codeWeekday,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedRoutesByWeekday, [
              userCode,
              codeWeekday,
            ]),
            returnValue: _i7.Future<List<_i37.PlannedRoute>>.value(
              <_i37.PlannedRoute>[],
            ),
          )
          as _i7.Future<List<_i37.PlannedRoute>>);

  @override
  _i7.Future<List<_i37.PlannedRoute>> getPlannedRoutesByClient(
    String? userCode,
    String? codeClient,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedRoutesByClient, [
              userCode,
              codeClient,
            ]),
            returnValue: _i7.Future<List<_i37.PlannedRoute>>.value(
              <_i37.PlannedRoute>[],
            ),
          )
          as _i7.Future<List<_i37.PlannedRoute>>);

  @override
  _i7.Future<List<int>> getUniqueWeekdays(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueWeekdays, [userCode]),
            returnValue: _i7.Future<List<int>>.value(<int>[]),
          )
          as _i7.Future<List<int>>);

  @override
  _i7.Future<void> deletePlannedRoutes(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlannedRoutes, [userCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearPlannedRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#clearPlannedRoutes, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveCreateOrder(_i19.CreateOrder? order) =>
      (super.noSuchMethod(
            Invocation.method(#saveCreateOrder, [order]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i19.CreateOrder>> getCreateOrders(
    String? codeAgent, {
    bool? isSynced,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCreateOrders,
              [codeAgent],
              {#isSynced: isSynced},
            ),
            returnValue: _i7.Future<List<_i19.CreateOrder>>.value(
              <_i19.CreateOrder>[],
            ),
          )
          as _i7.Future<List<_i19.CreateOrder>>);

  @override
  _i7.Future<_i19.CreateOrder?> getCreateOrderById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCreateOrderById, [id]),
            returnValue: _i7.Future<_i19.CreateOrder?>.value(),
          )
          as _i7.Future<_i19.CreateOrder?>);

  @override
  _i7.Future<void> updateCreateOrderSyncStatus(
    int? id,
    bool? isSynced, {
    String? syncError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCreateOrderSyncStatus,
              [id, isSynced],
              {#syncError: syncError},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteCreateOrder(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCreateOrder, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i19.CreateOrder>> getUnsyncedCreateOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedCreateOrders, []),
            returnValue: _i7.Future<List<_i19.CreateOrder>>.value(
              <_i19.CreateOrder>[],
            ),
          )
          as _i7.Future<List<_i19.CreateOrder>>);

  @override
  _i7.Future<void> clearCreateOrderData() =>
      (super.noSuchMethod(
            Invocation.method(#clearCreateOrderData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateClientCoordinates(
    String? clientCode,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientCoordinates, [
              clientCode,
              latitude,
              longitude,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> ensureSalesReqPermissionsTableExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureSalesReqPermissionsTableExists, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveUserOrganizations(
    String? userCode,
    List<_i21.UserOrganization>? organizations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserOrganizations, [
              userCode,
              organizations,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i21.UserOrganization>> getUserOrganizations(
    String? userCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrganizations, [userCode]),
            returnValue: _i7.Future<List<_i21.UserOrganization>>.value(
              <_i21.UserOrganization>[],
            ),
          )
          as _i7.Future<List<_i21.UserOrganization>>);

  @override
  _i7.Future<_i21.UserOrganization?> getUserOrganizationByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrganizationByCode, [code]),
            returnValue: _i7.Future<_i21.UserOrganization?>.value(),
          )
          as _i7.Future<_i21.UserOrganization?>);

  @override
  _i7.Future<void> saveUserOrganization(_i21.UserOrganization? organization) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserOrganization, [organization]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserOrganization(
    String? code,
    _i21.UserOrganization? organization,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserOrganization, [code, organization]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteUserOrganization(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserOrganization, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteUserOrganizationsByUserCode(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserOrganizationsByUserCode, [userCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i21.UserOrganization>> getAllUserOrganizations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserOrganizations, []),
            returnValue: _i7.Future<List<_i21.UserOrganization>>.value(
              <_i21.UserOrganization>[],
            ),
          )
          as _i7.Future<List<_i21.UserOrganization>>);

  @override
  _i7.Future<int> getUserOrganizationsCount(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrganizationsCount, [userCode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> ensureTableExists(
    String? tableName,
    String? createTableSql, [
    List<String>? indexSqls,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#ensureTableExists, [
              tableName,
              createTableSql,
              indexSqls,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, Map<String, dynamic>> getTableCreationSql() =>
      (super.noSuchMethod(
            Invocation.method(#getTableCreationSql, []),
            returnValue: <String, Map<String, dynamic>>{},
          )
          as Map<String, Map<String, dynamic>>);

  @override
  _i7.Future<void> ensureUserOrganizationsTableExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserOrganizationsTableExists, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> ensureOrderDetailsTablesExist() =>
      (super.noSuchMethod(
            Invocation.method(#ensureOrderDetailsTablesExist, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i38.Thumbnail>> getThumbnails() =>
      (super.noSuchMethod(
            Invocation.method(#getThumbnails, []),
            returnValue: _i7.Future<List<_i38.Thumbnail>>.value(
              <_i38.Thumbnail>[],
            ),
          )
          as _i7.Future<List<_i38.Thumbnail>>);

  @override
  _i7.Future<int> getTableRowCount(String? tableName) =>
      (super.noSuchMethod(
            Invocation.method(#getTableRowCount, [tableName]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> saveContractTypes(List<_i22.ContractType>? contractTypes) =>
      (super.noSuchMethod(
            Invocation.method(#saveContractTypes, [contractTypes]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i22.ContractType>> getContractTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getContractTypes, []),
            returnValue: _i7.Future<List<_i22.ContractType>>.value(
              <_i22.ContractType>[],
            ),
          )
          as _i7.Future<List<_i22.ContractType>>);

  @override
  _i7.Future<bool> hasContractTypes() =>
      (super.noSuchMethod(
            Invocation.method(#hasContractTypes, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> clearContractTypes() =>
      (super.noSuchMethod(
            Invocation.method(#clearContractTypes, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveDistrictContracting(
    List<_i23.DistrictContracting>? districts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveDistrictContracting, [districts]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i23.DistrictContracting>> getDistrictContracting() =>
      (super.noSuchMethod(
            Invocation.method(#getDistrictContracting, []),
            returnValue: _i7.Future<List<_i23.DistrictContracting>>.value(
              <_i23.DistrictContracting>[],
            ),
          )
          as _i7.Future<List<_i23.DistrictContracting>>);

  @override
  _i7.Future<bool> hasDistrictContracting() =>
      (super.noSuchMethod(
            Invocation.method(#hasDistrictContracting, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> clearDistrictContracting() =>
      (super.noSuchMethod(
            Invocation.method(#clearDistrictContracting, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveProductImages(
    List<_i39.ProductImage>? images, {
    String? productCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveProductImages,
              [images],
              {#productCode: productCode},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i39.ProductImage>> getProductImages(String? productCode) =>
      (super.noSuchMethod(
            Invocation.method(#getProductImages, [productCode]),
            returnValue: _i7.Future<List<_i39.ProductImage>>.value(
              <_i39.ProductImage>[],
            ),
          )
          as _i7.Future<List<_i39.ProductImage>>);

  @override
  _i7.Future<_i39.ProductImage?> getMainProductImage(String? productCode) =>
      (super.noSuchMethod(
            Invocation.method(#getMainProductImage, [productCode]),
            returnValue: _i7.Future<_i39.ProductImage?>.value(),
          )
          as _i7.Future<_i39.ProductImage?>);

  @override
  _i7.Future<List<_i39.ProductImage>> getAllProductImages() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProductImages, []),
            returnValue: _i7.Future<List<_i39.ProductImage>>.value(
              <_i39.ProductImage>[],
            ),
          )
          as _i7.Future<List<_i39.ProductImage>>);

  @override
  _i7.Future<bool> hasProductImages() =>
      (super.noSuchMethod(
            Invocation.method(#hasProductImages, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<int> getProductImagesCount() =>
      (super.noSuchMethod(
            Invocation.method(#getProductImagesCount, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> clearProductImages() =>
      (super.noSuchMethod(
            Invocation.method(#clearProductImages, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteProductImages(String? productCode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductImages, [productCode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i40.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i5.Database>.value(
              _FakeDatabase_3(this, Invocation.getter(#database)),
            ),
          )
          as _i7.Future<_i5.Database>);

  @override
  _i7.Future<void> saveUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [userData]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByCredentials(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCredentials, [username, password]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>?> getUserByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCode, [code]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> updateUser(String? code, Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [code, userData]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteUser(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllUsersExcept(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllUsersExcept, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateClientCoordinates(
    String? clientCode,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientCoordinates, [
              clientCode,
              latitude,
              longitude,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> getTableRowCount(String? tableName) =>
      (super.noSuchMethod(
            Invocation.method(#getTableRowCount, [tableName]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}
