// Mocks generated by Mockito 5.4.6 from annotations
// in gloria_marketing_flutter/test/business_region_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gloria_marketing_flutter/src/core/database/database_helper.dart'
    as _i26;
import 'package:gloria_marketing_flutter/src/core/services/api_database_service.dart'
    as _i16;
import 'package:gloria_marketing_flutter/src/core/services/shared_preferences_service.dart'
    as _i4;
import 'package:gloria_marketing_flutter/src/core/services/soap_api_service.dart'
    as _i6;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/akb_by_category.dart'
    as _i23;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region.dart'
    as _i8;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region_report.dart'
    as _i22;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/client_contract.dart'
    as _i15;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/kpi_data.dart'
    as _i2;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/main_report.dart'
    as _i21;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/price_type.dart'
    as _i12;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_balance.dart'
    as _i19;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_brand.dart'
    as _i17;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_data.dart'
    as _i11;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_price.dart'
    as _i13;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_series.dart'
    as _i18;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_with_price.dart'
    as _i20;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/trading_point.dart'
    as _i7;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/user_warehouse.dart'
    as _i9;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan.dart'
    as _i24;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan_list.dart'
    as _i25;
import 'package:gloria_marketing_flutter/src/features/marketing/data/models/promotion_model.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKpiData_0 extends _i1.SmartFake implements _i2.KpiData {
  _FakeKpiData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i4.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveCredentials(
    String? username,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [
              username,
              password,
              rememberMe,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveUserData({
    required String? userCode,
    required String? userName,
    required String? warehouseCode,
    required String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userCode: userCode,
              #userName: userName,
              #warehouseCode: warehouseCode,
              #codeProject: codeProject,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isRememberMeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isRememberMeEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> setServerName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setServerName, [name]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clearServerName() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerName, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setBaseUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setBaseUrl, [url]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clearBaseUrl() =>
      (super.noSuchMethod(
            Invocation.method(#clearBaseUrl, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setOfflineMode(bool? isOffline) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineMode, [isOffline]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#isOfflineMode, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> clearOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#clearOfflineMode, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SoapApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoapApiService extends _i1.Mock implements _i6.SoapApiService {
  MockSoapApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.KpiData> getKpiData({
    required String? userCode,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [], {
              #userCode: userCode,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.KpiData>.value(
              _FakeKpiData_0(
                this,
                Invocation.method(#getKpiData, [], {
                  #userCode: userCode,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.KpiData>);

  @override
  _i5.Future<List<_i7.TradingPoint>> getClients({
    required String? userCode,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClients, [], {
              #userCode: userCode,
              #password: password,
            }),
            returnValue: _i5.Future<List<_i7.TradingPoint>>.value(
              <_i7.TradingPoint>[],
            ),
          )
          as _i5.Future<List<_i7.TradingPoint>>);

  @override
  _i5.Future<List<_i8.BusinessRegion>> getBusinessRegions({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegions, [], {#userCode: userCode}),
            returnValue: _i5.Future<List<_i8.BusinessRegion>>.value(
              <_i8.BusinessRegion>[],
            ),
          )
          as _i5.Future<List<_i8.BusinessRegion>>);

  @override
  _i5.Future<List<_i9.UserWarehouse>> getWarehousesUser({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWarehousesUser, [], {#userCode: userCode}),
            returnValue: _i5.Future<List<_i9.UserWarehouse>>.value(
              <_i9.UserWarehouse>[],
            ),
          )
          as _i5.Future<List<_i9.UserWarehouse>>);

  @override
  _i5.Future<String> createBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i5.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> updateBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i5.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#updateBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> deleteBusinessRegion({
    required String? userCode,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
            }),
            returnValue: _i5.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#deleteBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> deleteAllBusinessRegions({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBusinessRegions, [], {
              #userCode: userCode,
            }),
            returnValue: _i5.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#deleteAllBusinessRegions, [], {
                  #userCode: userCode,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<_i11.ProductData>> getProducts({
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i5.Future<List<_i11.ProductData>>.value(
              <_i11.ProductData>[],
            ),
          )
          as _i5.Future<List<_i11.ProductData>>);

  @override
  _i5.Future<Map<String, dynamic>> getProductBalances({
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalances, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i12.PriceType>> getPriceTypes({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, [], {#userCode: userCode}),
            returnValue: _i5.Future<List<_i12.PriceType>>.value(
              <_i12.PriceType>[],
            ),
          )
          as _i5.Future<List<_i12.PriceType>>);

  @override
  _i5.Future<List<_i13.ProductPrice>> getProductPrices({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {#userCode: userCode}),
            returnValue: _i5.Future<List<_i13.ProductPrice>>.value(
              <_i13.ProductPrice>[],
            ),
          )
          as _i5.Future<List<_i13.ProductPrice>>);

  @override
  _i5.Future<List<_i14.PromotionModel>> getPromotions({String? authToken}) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotions, [], {#authToken: authToken}),
            returnValue: _i5.Future<List<_i14.PromotionModel>>.value(
              <_i14.PromotionModel>[],
            ),
          )
          as _i5.Future<List<_i14.PromotionModel>>);

  @override
  _i5.Future<List<_i15.ClientContract>> getAllContracts({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllContracts, [], {#userCode: userCode}),
            returnValue: _i5.Future<List<_i15.ClientContract>>.value(
              <_i15.ClientContract>[],
            ),
          )
          as _i5.Future<List<_i15.ClientContract>>);

  @override
  _i5.Future<Map<String, dynamic>> getReportByPeriod({
    required String? userCode,
    required String? dateStart,
    required String? dateEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReportByPeriod, [], {
              #userCode: userCode,
              #dateStart: dateStart,
              #dateEnd: dateEnd,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [ApiDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiDatabaseService extends _i1.Mock
    implements _i16.ApiDatabaseService {
  MockApiDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i5.Future<_i3.Database>);

  @override
  _i5.Future<void> saveKpiData(String? userCode, _i2.KpiData? kpiData) =>
      (super.noSuchMethod(
            Invocation.method(#saveKpiData, [userCode, kpiData]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.KpiData?> getKpiData(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [userCode]),
            returnValue: _i5.Future<_i2.KpiData?>.value(),
          )
          as _i5.Future<_i2.KpiData?>);

  @override
  _i5.Future<void> saveClients(List<_i7.TradingPoint>? clients) =>
      (super.noSuchMethod(
            Invocation.method(#saveClients, [clients]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.TradingPoint>> getClients() =>
      (super.noSuchMethod(
            Invocation.method(#getClients, []),
            returnValue: _i5.Future<List<_i7.TradingPoint>>.value(
              <_i7.TradingPoint>[],
            ),
          )
          as _i5.Future<List<_i7.TradingPoint>>);

  @override
  _i5.Future<void> saveProducts(List<_i11.ProductData>? products) =>
      (super.noSuchMethod(
            Invocation.method(#saveProducts, [products]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i11.ProductData>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i5.Future<List<_i11.ProductData>>.value(
              <_i11.ProductData>[],
            ),
          )
          as _i5.Future<List<_i11.ProductData>>);

  @override
  _i5.Future<void> savePriceTypes(List<_i12.PriceType>? priceTypes) =>
      (super.noSuchMethod(
            Invocation.method(#savePriceTypes, [priceTypes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i12.PriceType>> getPriceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, []),
            returnValue: _i5.Future<List<_i12.PriceType>>.value(
              <_i12.PriceType>[],
            ),
          )
          as _i5.Future<List<_i12.PriceType>>);

  @override
  _i5.Future<void> saveProductPrices(List<_i13.ProductPrice>? productPrices) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductPrices, [productPrices]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i13.ProductPrice>> getProductPrices({
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i5.Future<List<_i13.ProductPrice>>.value(
              <_i13.ProductPrice>[],
            ),
          )
          as _i5.Future<List<_i13.ProductPrice>>);

  @override
  _i5.Future<void> savePromotions(List<_i14.PromotionModel>? promotions) =>
      (super.noSuchMethod(
            Invocation.method(#savePromotions, [promotions]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i14.PromotionModel>> getPromotions({
    bool? onlyActive = true,
    String? searchQuery,
    DateTime? dateFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotions, [], {
              #onlyActive: onlyActive,
              #searchQuery: searchQuery,
              #dateFilter: dateFilter,
            }),
            returnValue: _i5.Future<List<_i14.PromotionModel>>.value(
              <_i14.PromotionModel>[],
            ),
          )
          as _i5.Future<List<_i14.PromotionModel>>);

  @override
  _i5.Future<_i14.PromotionModel?> getPromotionByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotionByCode, [code]),
            returnValue: _i5.Future<_i14.PromotionModel?>.value(),
          )
          as _i5.Future<_i14.PromotionModel?>);

  @override
  _i5.Future<void> updatePromotionSyncTime(String? code, DateTime? syncTime) =>
      (super.noSuchMethod(
            Invocation.method(#updatePromotionSyncTime, [code, syncTime]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletePromotion(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deletePromotion, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getPromotionCount({bool? onlyActive = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotionCount, [], {
              #onlyActive: onlyActive,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> saveBusinessRegions(List<_i8.BusinessRegion>? regions) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegions, [regions]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.BusinessRegion>> getBusinessRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegions, []),
            returnValue: _i5.Future<List<_i8.BusinessRegion>>.value(
              <_i8.BusinessRegion>[],
            ),
          )
          as _i5.Future<List<_i8.BusinessRegion>>);

  @override
  _i5.Future<_i8.BusinessRegion?> getBusinessRegionByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegionByCode, [code]),
            returnValue: _i5.Future<_i8.BusinessRegion?>.value(),
          )
          as _i5.Future<_i8.BusinessRegion?>);

  @override
  _i5.Future<void> saveBusinessRegion(_i8.BusinessRegion? region) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegion, [region]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateBusinessRegion(
    String? code,
    _i8.BusinessRegion? region,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [code, region]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteBusinessRegion(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveUserWarehouses(List<_i9.UserWarehouse>? warehouses) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserWarehouses, [warehouses]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.UserWarehouse>> getUserWarehouses() =>
      (super.noSuchMethod(
            Invocation.method(#getUserWarehouses, []),
            returnValue: _i5.Future<List<_i9.UserWarehouse>>.value(
              <_i9.UserWarehouse>[],
            ),
          )
          as _i5.Future<List<_i9.UserWarehouse>>);

  @override
  _i5.Future<_i9.UserWarehouse?> getUserWarehouseByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWarehouseByCode, [code]),
            returnValue: _i5.Future<_i9.UserWarehouse?>.value(),
          )
          as _i5.Future<_i9.UserWarehouse?>);

  @override
  _i5.Future<void> saveUserWarehouse(_i9.UserWarehouse? warehouse) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserWarehouse, [warehouse]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserWarehouse(
    String? code,
    _i9.UserWarehouse? warehouse,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserWarehouse, [code, warehouse]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUserWarehouse(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserWarehouse, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveProductBrands(List<_i17.ProductBrand>? brands) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBrands, [brands]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i17.ProductBrand>> getProductBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getProductBrands, []),
            returnValue: _i5.Future<List<_i17.ProductBrand>>.value(
              <_i17.ProductBrand>[],
            ),
          )
          as _i5.Future<List<_i17.ProductBrand>>);

  @override
  _i5.Future<_i17.ProductBrand?> getProductBrandByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBrandByName, [name]),
            returnValue: _i5.Future<_i17.ProductBrand?>.value(),
          )
          as _i5.Future<_i17.ProductBrand?>);

  @override
  _i5.Future<void> saveProductBrand(_i17.ProductBrand? brand) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBrand, [brand]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProductBrand(String? name, _i17.ProductBrand? brand) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductBrand, [name, brand]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProductBrand(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductBrand, [name]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveProductSeries(List<_i18.ProductSeries>? series) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductSeries, [series]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i18.ProductSeries>> getProductSeries({String? brandName}) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSeries, [], {#brandName: brandName}),
            returnValue: _i5.Future<List<_i18.ProductSeries>>.value(
              <_i18.ProductSeries>[],
            ),
          )
          as _i5.Future<List<_i18.ProductSeries>>);

  @override
  _i5.Future<_i18.ProductSeries?> getProductSeriesByNameAndBrand(
    String? name,
    String? brandName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSeriesByNameAndBrand, [
              name,
              brandName,
            ]),
            returnValue: _i5.Future<_i18.ProductSeries?>.value(),
          )
          as _i5.Future<_i18.ProductSeries?>);

  @override
  _i5.Future<void> saveProductSerie(_i18.ProductSeries? series) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductSerie, [series]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProductSeries(
    String? name,
    String? brandName,
    _i18.ProductSeries? series,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductSeries, [name, brandName, series]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProductSeries(String? name, String? brandName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductSeries, [name, brandName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveProductBalances(List<_i19.ProductBalance>? balances) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBalances, [balances]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i19.ProductBalance>> getProductBalances({
    String? warehouseCode,
    String? productBrand,
    String? productSeries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalances, [], {
              #warehouseCode: warehouseCode,
              #productBrand: productBrand,
              #productSeries: productSeries,
            }),
            returnValue: _i5.Future<List<_i19.ProductBalance>>.value(
              <_i19.ProductBalance>[],
            ),
          )
          as _i5.Future<List<_i19.ProductBalance>>);

  @override
  _i5.Future<_i19.ProductBalance?> getProductBalanceByCodes(
    String? warehouseCode,
    String? productCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalanceByCodes, [
              warehouseCode,
              productCode,
            ]),
            returnValue: _i5.Future<_i19.ProductBalance?>.value(),
          )
          as _i5.Future<_i19.ProductBalance?>);

  @override
  _i5.Future<void> saveProductBalance(_i19.ProductBalance? balance) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBalance, [balance]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProductBalance(
    String? warehouseCode,
    String? productCode,
    _i19.ProductBalance? balance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductBalance, [
              warehouseCode,
              productCode,
              balance,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProductBalance(
    String? warehouseCode,
    String? productCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductBalance, [
              warehouseCode,
              productCode,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i20.ProductWithPrice>> getProductsWithPrices({
    required String? priceTypeCode,
    List<String>? warehouseCodes,
    String? searchQuery,
    String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsWithPrices, [], {
              #priceTypeCode: priceTypeCode,
              #warehouseCodes: warehouseCodes,
              #searchQuery: searchQuery,
              #codeProject: codeProject,
            }),
            returnValue: _i5.Future<List<_i20.ProductWithPrice>>.value(
              <_i20.ProductWithPrice>[],
            ),
          )
          as _i5.Future<List<_i20.ProductWithPrice>>);

  @override
  _i5.Future<void> saveClientContracts(List<_i15.ClientContract>? contracts) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientContracts, [contracts]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i15.ClientContract>> getClientContracts({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContracts, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i5.Future<List<_i15.ClientContract>>.value(
              <_i15.ClientContract>[],
            ),
          )
          as _i5.Future<List<_i15.ClientContract>>);

  @override
  _i5.Future<_i15.ClientContract?> getClientContractByCode(
    String? codeContract,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContractByCode, [codeContract]),
            returnValue: _i5.Future<_i15.ClientContract?>.value(),
          )
          as _i5.Future<_i15.ClientContract?>);

  @override
  _i5.Future<void> saveClientContract(_i15.ClientContract? contract) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientContract, [contract]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateClientContract(
    String? codeContract,
    _i15.ClientContract? contract,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientContract, [codeContract, contract]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteClientContract(String? codeContract) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClientContract, [codeContract]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveMainReports(List<_i21.MainReport>? reports) =>
      (super.noSuchMethod(
            Invocation.method(#saveMainReports, [reports]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i21.MainReport>> getMainReports({String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getMainReports, [], {#userCode: userCode}),
            returnValue: _i5.Future<List<_i21.MainReport>>.value(
              <_i21.MainReport>[],
            ),
          )
          as _i5.Future<List<_i21.MainReport>>);

  @override
  _i5.Future<_i21.MainReport?> getMainReportById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMainReportById, [id]),
            returnValue: _i5.Future<_i21.MainReport?>.value(),
          )
          as _i5.Future<_i21.MainReport?>);

  @override
  _i5.Future<void> saveBusinessRegionReports(
    List<_i22.BusinessRegionReport>? reports,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegionReports, [reports]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i22.BusinessRegionReport>> getBusinessRegionReports({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegionReports, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i5.Future<List<_i22.BusinessRegionReport>>.value(
              <_i22.BusinessRegionReport>[],
            ),
          )
          as _i5.Future<List<_i22.BusinessRegionReport>>);

  @override
  _i5.Future<void> saveAKBByCategories(List<_i23.AKBByCategory>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#saveAKBByCategories, [categories]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i23.AKBByCategory>> getAKBByCategories({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAKBByCategories, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i5.Future<List<_i23.AKBByCategory>>.value(
              <_i23.AKBByCategory>[],
            ),
          )
          as _i5.Future<List<_i23.AKBByCategory>>);

  @override
  _i5.Future<void> saveVisitPlans(List<_i24.VisitPlan>? plans) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitPlans, [plans]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i24.VisitPlan>> getVisitPlans({
    int? mainReportId,
    String? clientCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitPlans, [], {
              #mainReportId: mainReportId,
              #clientCode: clientCode,
            }),
            returnValue: _i5.Future<List<_i24.VisitPlan>>.value(
              <_i24.VisitPlan>[],
            ),
          )
          as _i5.Future<List<_i24.VisitPlan>>);

  @override
  _i5.Future<void> saveVisitPlanLists(List<_i25.VisitPlanList>? lists) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitPlanLists, [lists]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i25.VisitPlanList>> getVisitPlanLists({int? visitPlanId}) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitPlanLists, [], {
              #visitPlanId: visitPlanId,
            }),
            returnValue: _i5.Future<List<_i25.VisitPlanList>>.value(
              <_i25.VisitPlanList>[],
            ),
          )
          as _i5.Future<List<_i25.VisitPlanList>>);

  @override
  _i5.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i26.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i5.Future<_i3.Database>);

  @override
  _i5.Future<void> saveUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [userData]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserByCredentials(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCredentials, [username, password]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCode, [code]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateUser(String? code, Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [code, userData]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllUsersExcept(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllUsersExcept, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
