// Mocks generated by Mockito 5.4.6 from annotations
// in gloria_marketing_flutter/test/main_report_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:gloria_marketing_flutter/src/core/database/database_helper.dart'
    as _i28;
import 'package:gloria_marketing_flutter/src/core/services/api_database_service.dart'
    as _i7;
import 'package:gloria_marketing_flutter/src/core/services/data_sync_service.dart'
    as _i26;
import 'package:gloria_marketing_flutter/src/core/services/shared_preferences_service.dart'
    as _i5;
import 'package:gloria_marketing_flutter/src/core/services/soap_api_service.dart'
    as _i24;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/akb_by_category.dart'
    as _i21;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region.dart'
    as _i4;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region_report.dart'
    as _i20;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/client_contract.dart'
    as _i18;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/kpi_data.dart'
    as _i3;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/main_report.dart'
    as _i19;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/price_type.dart'
    as _i10;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_balance.dart'
    as _i16;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_brand.dart'
    as _i14;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_data.dart'
    as _i9;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_price.dart'
    as _i11;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_series.dart'
    as _i15;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_with_price.dart'
    as _i17;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/trading_point.dart'
    as _i8;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/user_warehouse.dart'
    as _i13;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan.dart'
    as _i22;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/visit_plan_list.dart'
    as _i23;
import 'package:gloria_marketing_flutter/src/features/agent/presentation/widgets/data_sync_progress_widget.dart'
    as _i27;
import 'package:gloria_marketing_flutter/src/features/marketing/data/models/promotion_model.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKpiData_1 extends _i1.SmartFake implements _i3.KpiData {
  _FakeKpiData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBusinessRegion_2 extends _i1.SmartFake
    implements _i4.BusinessRegion {
  _FakeBusinessRegion_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i5.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveCredentials(
    String? username,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [
              username,
              password,
              rememberMe,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveUserData({
    required String? userCode,
    required String? userName,
    required String? warehouseCode,
    required String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userCode: userCode,
              #userName: userName,
              #warehouseCode: warehouseCode,
              #codeProject: codeProject,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isRememberMeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isRememberMeEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> setServerName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setServerName, [name]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> clearServerName() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerName, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setBaseUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setBaseUrl, [url]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> clearBaseUrl() =>
      (super.noSuchMethod(
            Invocation.method(#clearBaseUrl, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> setOfflineMode(bool? isOffline) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineMode, [isOffline]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#isOfflineMode, []),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> clearOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#clearOfflineMode, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ApiDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiDatabaseService extends _i1.Mock
    implements _i7.ApiDatabaseService {
  MockApiDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> saveKpiData(String? userCode, _i3.KpiData? kpiData) =>
      (super.noSuchMethod(
            Invocation.method(#saveKpiData, [userCode, kpiData]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.KpiData?> getKpiData(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [userCode]),
            returnValue: _i6.Future<_i3.KpiData?>.value(),
          )
          as _i6.Future<_i3.KpiData?>);

  @override
  _i6.Future<void> saveClients(List<_i8.TradingPoint>? clients) =>
      (super.noSuchMethod(
            Invocation.method(#saveClients, [clients]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.TradingPoint>> getClients() =>
      (super.noSuchMethod(
            Invocation.method(#getClients, []),
            returnValue: _i6.Future<List<_i8.TradingPoint>>.value(
              <_i8.TradingPoint>[],
            ),
          )
          as _i6.Future<List<_i8.TradingPoint>>);

  @override
  _i6.Future<void> saveProducts(List<_i9.ProductData>? products) =>
      (super.noSuchMethod(
            Invocation.method(#saveProducts, [products]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.ProductData>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i6.Future<List<_i9.ProductData>>.value(
              <_i9.ProductData>[],
            ),
          )
          as _i6.Future<List<_i9.ProductData>>);

  @override
  _i6.Future<void> savePriceTypes(List<_i10.PriceType>? priceTypes) =>
      (super.noSuchMethod(
            Invocation.method(#savePriceTypes, [priceTypes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.PriceType>> getPriceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, []),
            returnValue: _i6.Future<List<_i10.PriceType>>.value(
              <_i10.PriceType>[],
            ),
          )
          as _i6.Future<List<_i10.PriceType>>);

  @override
  _i6.Future<void> saveProductPrices(List<_i11.ProductPrice>? productPrices) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductPrices, [productPrices]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.ProductPrice>> getProductPrices({
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i6.Future<List<_i11.ProductPrice>>.value(
              <_i11.ProductPrice>[],
            ),
          )
          as _i6.Future<List<_i11.ProductPrice>>);

  @override
  _i6.Future<void> savePromotions(List<_i12.PromotionModel>? promotions) =>
      (super.noSuchMethod(
            Invocation.method(#savePromotions, [promotions]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.PromotionModel>> getPromotions({
    bool? onlyActive = true,
    String? searchQuery,
    DateTime? dateFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotions, [], {
              #onlyActive: onlyActive,
              #searchQuery: searchQuery,
              #dateFilter: dateFilter,
            }),
            returnValue: _i6.Future<List<_i12.PromotionModel>>.value(
              <_i12.PromotionModel>[],
            ),
          )
          as _i6.Future<List<_i12.PromotionModel>>);

  @override
  _i6.Future<_i12.PromotionModel?> getPromotionByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotionByCode, [code]),
            returnValue: _i6.Future<_i12.PromotionModel?>.value(),
          )
          as _i6.Future<_i12.PromotionModel?>);

  @override
  _i6.Future<void> updatePromotionSyncTime(String? code, DateTime? syncTime) =>
      (super.noSuchMethod(
            Invocation.method(#updatePromotionSyncTime, [code, syncTime]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletePromotion(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deletePromotion, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getPromotionCount({bool? onlyActive = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotionCount, [], {
              #onlyActive: onlyActive,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> saveBusinessRegions(List<_i4.BusinessRegion>? regions) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegions, [regions]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.BusinessRegion>> getBusinessRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegions, []),
            returnValue: _i6.Future<List<_i4.BusinessRegion>>.value(
              <_i4.BusinessRegion>[],
            ),
          )
          as _i6.Future<List<_i4.BusinessRegion>>);

  @override
  _i6.Future<_i4.BusinessRegion?> getBusinessRegionByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegionByCode, [code]),
            returnValue: _i6.Future<_i4.BusinessRegion?>.value(),
          )
          as _i6.Future<_i4.BusinessRegion?>);

  @override
  _i6.Future<void> saveBusinessRegion(_i4.BusinessRegion? region) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegion, [region]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateBusinessRegion(
    String? code,
    _i4.BusinessRegion? region,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [code, region]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteBusinessRegion(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveUserWarehouses(List<_i13.UserWarehouse>? warehouses) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserWarehouses, [warehouses]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.UserWarehouse>> getUserWarehouses() =>
      (super.noSuchMethod(
            Invocation.method(#getUserWarehouses, []),
            returnValue: _i6.Future<List<_i13.UserWarehouse>>.value(
              <_i13.UserWarehouse>[],
            ),
          )
          as _i6.Future<List<_i13.UserWarehouse>>);

  @override
  _i6.Future<_i13.UserWarehouse?> getUserWarehouseByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWarehouseByCode, [code]),
            returnValue: _i6.Future<_i13.UserWarehouse?>.value(),
          )
          as _i6.Future<_i13.UserWarehouse?>);

  @override
  _i6.Future<void> saveUserWarehouse(_i13.UserWarehouse? warehouse) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserWarehouse, [warehouse]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserWarehouse(
    String? code,
    _i13.UserWarehouse? warehouse,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserWarehouse, [code, warehouse]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUserWarehouse(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserWarehouse, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveProductBrands(List<_i14.ProductBrand>? brands) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBrands, [brands]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.ProductBrand>> getProductBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getProductBrands, []),
            returnValue: _i6.Future<List<_i14.ProductBrand>>.value(
              <_i14.ProductBrand>[],
            ),
          )
          as _i6.Future<List<_i14.ProductBrand>>);

  @override
  _i6.Future<_i14.ProductBrand?> getProductBrandByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBrandByName, [name]),
            returnValue: _i6.Future<_i14.ProductBrand?>.value(),
          )
          as _i6.Future<_i14.ProductBrand?>);

  @override
  _i6.Future<void> saveProductBrand(_i14.ProductBrand? brand) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBrand, [brand]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProductBrand(String? name, _i14.ProductBrand? brand) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductBrand, [name, brand]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProductBrand(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductBrand, [name]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveProductSeries(List<_i15.ProductSeries>? series) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductSeries, [series]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i15.ProductSeries>> getProductSeries({String? brandName}) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSeries, [], {#brandName: brandName}),
            returnValue: _i6.Future<List<_i15.ProductSeries>>.value(
              <_i15.ProductSeries>[],
            ),
          )
          as _i6.Future<List<_i15.ProductSeries>>);

  @override
  _i6.Future<_i15.ProductSeries?> getProductSeriesByNameAndBrand(
    String? name,
    String? brandName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSeriesByNameAndBrand, [
              name,
              brandName,
            ]),
            returnValue: _i6.Future<_i15.ProductSeries?>.value(),
          )
          as _i6.Future<_i15.ProductSeries?>);

  @override
  _i6.Future<void> saveProductSerie(_i15.ProductSeries? series) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductSerie, [series]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProductSeries(
    String? name,
    String? brandName,
    _i15.ProductSeries? series,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductSeries, [name, brandName, series]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProductSeries(String? name, String? brandName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductSeries, [name, brandName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveProductBalances(List<_i16.ProductBalance>? balances) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBalances, [balances]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i16.ProductBalance>> getProductBalances({
    String? warehouseCode,
    String? productBrand,
    String? productSeries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalances, [], {
              #warehouseCode: warehouseCode,
              #productBrand: productBrand,
              #productSeries: productSeries,
            }),
            returnValue: _i6.Future<List<_i16.ProductBalance>>.value(
              <_i16.ProductBalance>[],
            ),
          )
          as _i6.Future<List<_i16.ProductBalance>>);

  @override
  _i6.Future<_i16.ProductBalance?> getProductBalanceByCodes(
    String? warehouseCode,
    String? productCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalanceByCodes, [
              warehouseCode,
              productCode,
            ]),
            returnValue: _i6.Future<_i16.ProductBalance?>.value(),
          )
          as _i6.Future<_i16.ProductBalance?>);

  @override
  _i6.Future<void> saveProductBalance(_i16.ProductBalance? balance) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductBalance, [balance]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProductBalance(
    String? warehouseCode,
    String? productCode,
    _i16.ProductBalance? balance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductBalance, [
              warehouseCode,
              productCode,
              balance,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProductBalance(
    String? warehouseCode,
    String? productCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductBalance, [
              warehouseCode,
              productCode,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i17.ProductWithPrice>> getProductsWithPrices({
    required String? priceTypeCode,
    List<String>? warehouseCodes,
    String? searchQuery,
    String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsWithPrices, [], {
              #priceTypeCode: priceTypeCode,
              #warehouseCodes: warehouseCodes,
              #searchQuery: searchQuery,
              #codeProject: codeProject,
            }),
            returnValue: _i6.Future<List<_i17.ProductWithPrice>>.value(
              <_i17.ProductWithPrice>[],
            ),
          )
          as _i6.Future<List<_i17.ProductWithPrice>>);

  @override
  _i6.Future<void> saveClientContracts(List<_i18.ClientContract>? contracts) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientContracts, [contracts]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i18.ClientContract>> getClientContracts({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContracts, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i6.Future<List<_i18.ClientContract>>.value(
              <_i18.ClientContract>[],
            ),
          )
          as _i6.Future<List<_i18.ClientContract>>);

  @override
  _i6.Future<_i18.ClientContract?> getClientContractByCode(
    String? codeContract,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getClientContractByCode, [codeContract]),
            returnValue: _i6.Future<_i18.ClientContract?>.value(),
          )
          as _i6.Future<_i18.ClientContract?>);

  @override
  _i6.Future<void> saveClientContract(_i18.ClientContract? contract) =>
      (super.noSuchMethod(
            Invocation.method(#saveClientContract, [contract]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateClientContract(
    String? codeContract,
    _i18.ClientContract? contract,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientContract, [codeContract, contract]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteClientContract(String? codeContract) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClientContract, [codeContract]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveMainReports(List<_i19.MainReport>? reports) =>
      (super.noSuchMethod(
            Invocation.method(#saveMainReports, [reports]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i19.MainReport>> getMainReports({String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getMainReports, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i19.MainReport>>.value(
              <_i19.MainReport>[],
            ),
          )
          as _i6.Future<List<_i19.MainReport>>);

  @override
  _i6.Future<_i19.MainReport?> getMainReportById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMainReportById, [id]),
            returnValue: _i6.Future<_i19.MainReport?>.value(),
          )
          as _i6.Future<_i19.MainReport?>);

  @override
  _i6.Future<void> saveBusinessRegionReports(
    List<_i20.BusinessRegionReport>? reports,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveBusinessRegionReports, [reports]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i20.BusinessRegionReport>> getBusinessRegionReports({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegionReports, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i6.Future<List<_i20.BusinessRegionReport>>.value(
              <_i20.BusinessRegionReport>[],
            ),
          )
          as _i6.Future<List<_i20.BusinessRegionReport>>);

  @override
  _i6.Future<void> saveAKBByCategories(List<_i21.AKBByCategory>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#saveAKBByCategories, [categories]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i21.AKBByCategory>> getAKBByCategories({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAKBByCategories, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i6.Future<List<_i21.AKBByCategory>>.value(
              <_i21.AKBByCategory>[],
            ),
          )
          as _i6.Future<List<_i21.AKBByCategory>>);

  @override
  _i6.Future<void> saveVisitPlans(List<_i22.VisitPlan>? plans) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitPlans, [plans]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i22.VisitPlan>> getVisitPlans({
    int? mainReportId,
    String? clientCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitPlans, [], {
              #mainReportId: mainReportId,
              #clientCode: clientCode,
            }),
            returnValue: _i6.Future<List<_i22.VisitPlan>>.value(
              <_i22.VisitPlan>[],
            ),
          )
          as _i6.Future<List<_i22.VisitPlan>>);

  @override
  _i6.Future<void> saveVisitPlanLists(List<_i23.VisitPlanList>? lists) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitPlanLists, [lists]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i23.VisitPlanList>> getVisitPlanLists({int? visitPlanId}) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitPlanLists, [], {
              #visitPlanId: visitPlanId,
            }),
            returnValue: _i6.Future<List<_i23.VisitPlanList>>.value(
              <_i23.VisitPlanList>[],
            ),
          )
          as _i6.Future<List<_i23.VisitPlanList>>);

  @override
  _i6.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SoapApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoapApiService extends _i1.Mock implements _i24.SoapApiService {
  MockSoapApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.KpiData> getKpiData({
    required String? userCode,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [], {
              #userCode: userCode,
              #password: password,
            }),
            returnValue: _i6.Future<_i3.KpiData>.value(
              _FakeKpiData_1(
                this,
                Invocation.method(#getKpiData, [], {
                  #userCode: userCode,
                  #password: password,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.KpiData>);

  @override
  _i6.Future<List<_i8.TradingPoint>> getClients({
    required String? userCode,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClients, [], {
              #userCode: userCode,
              #password: password,
            }),
            returnValue: _i6.Future<List<_i8.TradingPoint>>.value(
              <_i8.TradingPoint>[],
            ),
          )
          as _i6.Future<List<_i8.TradingPoint>>);

  @override
  _i6.Future<List<_i4.BusinessRegion>> getBusinessRegions({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBusinessRegions, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i4.BusinessRegion>>.value(
              <_i4.BusinessRegion>[],
            ),
          )
          as _i6.Future<List<_i4.BusinessRegion>>);

  @override
  _i6.Future<List<_i13.UserWarehouse>> getWarehousesUser({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWarehousesUser, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i13.UserWarehouse>>.value(
              <_i13.UserWarehouse>[],
            ),
          )
          as _i6.Future<List<_i13.UserWarehouse>>);

  @override
  _i6.Future<String> createBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i6.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#createBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> updateBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i6.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#updateBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> deleteBusinessRegion({
    required String? userCode,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
            }),
            returnValue: _i6.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#deleteBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> deleteAllBusinessRegions({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBusinessRegions, [], {
              #userCode: userCode,
            }),
            returnValue: _i6.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#deleteAllBusinessRegions, [], {
                  #userCode: userCode,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i9.ProductData>> getProducts({
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i6.Future<List<_i9.ProductData>>.value(
              <_i9.ProductData>[],
            ),
          )
          as _i6.Future<List<_i9.ProductData>>);

  @override
  _i6.Future<Map<String, dynamic>> getProductBalances({
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBalances, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i10.PriceType>> getPriceTypes({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i10.PriceType>>.value(
              <_i10.PriceType>[],
            ),
          )
          as _i6.Future<List<_i10.PriceType>>);

  @override
  _i6.Future<List<_i11.ProductPrice>> getProductPrices({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i11.ProductPrice>>.value(
              <_i11.ProductPrice>[],
            ),
          )
          as _i6.Future<List<_i11.ProductPrice>>);

  @override
  _i6.Future<List<_i12.PromotionModel>> getPromotions({String? authToken}) =>
      (super.noSuchMethod(
            Invocation.method(#getPromotions, [], {#authToken: authToken}),
            returnValue: _i6.Future<List<_i12.PromotionModel>>.value(
              <_i12.PromotionModel>[],
            ),
          )
          as _i6.Future<List<_i12.PromotionModel>>);

  @override
  _i6.Future<List<_i18.ClientContract>> getAllContracts({
    required String? userCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllContracts, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i18.ClientContract>>.value(
              <_i18.ClientContract>[],
            ),
          )
          as _i6.Future<List<_i18.ClientContract>>);

  @override
  _i6.Future<Map<String, dynamic>> getReportByPeriod({
    required String? userCode,
    required String? dateStart,
    required String? dateEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReportByPeriod, [], {
              #userCode: userCode,
              #dateStart: dateStart,
              #dateEnd: dateEnd,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [DataSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSyncService extends _i1.Mock implements _i26.DataSyncService {
  MockDataSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> registerBackgroundSync({
    Duration? frequency = const Duration(hours: 6),
    String? userCode,
    String? password,
    String? codeProject,
    String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerBackgroundSync, [], {
              #frequency: frequency,
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelBackgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#cancelBackgroundSync, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> registerRetrySync({
    required Map<String, dynamic>? failedOperation,
    Duration? delay = const Duration(minutes: 15),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerRetrySync, [], {
              #failedOperation: failedOperation,
              #delay: delay,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> validateUserWithDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#validateUserWithDatabase, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> syncUserDataWithDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#syncUserDataWithDatabase, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllCachedData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCachedData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncAllUserData({
    required String? userCode,
    required String? password,
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllUserData, [], {
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<_i27.SyncStep> syncAllUserDataWithProgress({
    required String? userCode,
    required String? password,
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllUserDataWithProgress, [], {
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i6.Stream<_i27.SyncStep>.empty(),
          )
          as _i6.Stream<_i27.SyncStep>);

  @override
  _i6.Future<_i3.KpiData> syncKpiData({
    required String? userCode,
    required String? password,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncKpiData, [], {
              #userCode: userCode,
              #password: password,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<_i3.KpiData>.value(
              _FakeKpiData_1(
                this,
                Invocation.method(#syncKpiData, [], {
                  #userCode: userCode,
                  #password: password,
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.KpiData>);

  @override
  _i6.Future<List<_i8.TradingPoint>> syncClients({
    required String? userCode,
    required String? password,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncClients, [], {
              #userCode: userCode,
              #password: password,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i8.TradingPoint>>.value(
              <_i8.TradingPoint>[],
            ),
          )
          as _i6.Future<List<_i8.TradingPoint>>);

  @override
  _i6.Future<List<_i9.ProductData>> syncProducts({
    required String? codeProject,
    required String? codeSklad,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncProducts, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i9.ProductData>>.value(
              <_i9.ProductData>[],
            ),
          )
          as _i6.Future<List<_i9.ProductData>>);

  @override
  _i6.Future<List<_i10.PriceType>> syncPriceTypes({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncPriceTypes, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i10.PriceType>>.value(
              <_i10.PriceType>[],
            ),
          )
          as _i6.Future<List<_i10.PriceType>>);

  @override
  _i6.Future<List<_i11.ProductPrice>> syncProductPrices({
    required String? userCode,
    bool? forceRefresh = false,
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncProductPrices, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i6.Future<List<_i11.ProductPrice>>.value(
              <_i11.ProductPrice>[],
            ),
          )
          as _i6.Future<List<_i11.ProductPrice>>);

  @override
  _i6.Future<List<_i4.BusinessRegion>> syncBusinessRegions({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncBusinessRegions, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i4.BusinessRegion>>.value(
              <_i4.BusinessRegion>[],
            ),
          )
          as _i6.Future<List<_i4.BusinessRegion>>);

  @override
  _i6.Future<List<_i13.UserWarehouse>> syncUserWarehouses({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserWarehouses, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i13.UserWarehouse>>.value(
              <_i13.UserWarehouse>[],
            ),
          )
          as _i6.Future<List<_i13.UserWarehouse>>);

  @override
  _i6.Future<Map<String, dynamic>> syncProductBalances({
    required String? codeProject,
    required String? codeSklad,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncProductBalances, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i4.BusinessRegion> createBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i6.Future<_i4.BusinessRegion>.value(
              _FakeBusinessRegion_2(
                this,
                Invocation.method(#createBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BusinessRegion>);

  @override
  _i6.Future<_i4.BusinessRegion> updateBusinessRegion({
    required String? userCode,
    required String? code,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
              #name: name,
            }),
            returnValue: _i6.Future<_i4.BusinessRegion>.value(
              _FakeBusinessRegion_2(
                this,
                Invocation.method(#updateBusinessRegion, [], {
                  #userCode: userCode,
                  #code: code,
                  #name: name,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.BusinessRegion>);

  @override
  _i6.Future<void> deleteBusinessRegion({
    required String? userCode,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBusinessRegion, [], {
              #userCode: userCode,
              #code: code,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAllBusinessRegions({required String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBusinessRegions, [], {
              #userCode: userCode,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.PromotionModel>> syncPromotions({
    String? authToken,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncPromotions, [], {
              #authToken: authToken,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i12.PromotionModel>>.value(
              <_i12.PromotionModel>[],
            ),
          )
          as _i6.Future<List<_i12.PromotionModel>>);

  @override
  _i6.Future<List<_i18.ClientContract>> syncClientContracts({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncClientContracts, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<List<_i18.ClientContract>>.value(
              <_i18.ClientContract>[],
            ),
          )
          as _i6.Future<List<_i18.ClientContract>>);

  @override
  _i6.Future<Map<String, dynamic>> syncReportByPeriod({
    required String? userCode,
    required String? dateStart,
    required String? dateEnd,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncReportByPeriod, [], {
              #userCode: userCode,
              #dateStart: dateStart,
              #dateEnd: dateEnd,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.KpiData?> getCachedKpiData(String? userCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedKpiData, [userCode]),
            returnValue: _i6.Future<_i3.KpiData?>.value(),
          )
          as _i6.Future<_i3.KpiData?>);

  @override
  _i6.Future<List<_i8.TradingPoint>> getCachedClients() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedClients, []),
            returnValue: _i6.Future<List<_i8.TradingPoint>>.value(
              <_i8.TradingPoint>[],
            ),
          )
          as _i6.Future<List<_i8.TradingPoint>>);

  @override
  _i6.Future<List<_i9.ProductData>> getCachedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProducts, []),
            returnValue: _i6.Future<List<_i9.ProductData>>.value(
              <_i9.ProductData>[],
            ),
          )
          as _i6.Future<List<_i9.ProductData>>);

  @override
  _i6.Future<List<_i10.PriceType>> getCachedPriceTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPriceTypes, []),
            returnValue: _i6.Future<List<_i10.PriceType>>.value(
              <_i10.PriceType>[],
            ),
          )
          as _i6.Future<List<_i10.PriceType>>);

  @override
  _i6.Future<List<_i11.ProductPrice>> getCachedProductPrices({
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductPrices, [], {
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i6.Future<List<_i11.ProductPrice>>.value(
              <_i11.ProductPrice>[],
            ),
          )
          as _i6.Future<List<_i11.ProductPrice>>);

  @override
  _i6.Future<List<_i4.BusinessRegion>> getCachedBusinessRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBusinessRegions, []),
            returnValue: _i6.Future<List<_i4.BusinessRegion>>.value(
              <_i4.BusinessRegion>[],
            ),
          )
          as _i6.Future<List<_i4.BusinessRegion>>);

  @override
  _i6.Future<List<_i13.UserWarehouse>> getCachedUserWarehouses() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUserWarehouses, []),
            returnValue: _i6.Future<List<_i13.UserWarehouse>>.value(
              <_i13.UserWarehouse>[],
            ),
          )
          as _i6.Future<List<_i13.UserWarehouse>>);

  @override
  _i6.Future<List<_i16.ProductBalance>> getCachedProductBalances({
    String? warehouseCode,
    String? productBrand,
    String? productSeries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductBalances, [], {
              #warehouseCode: warehouseCode,
              #productBrand: productBrand,
              #productSeries: productSeries,
            }),
            returnValue: _i6.Future<List<_i16.ProductBalance>>.value(
              <_i16.ProductBalance>[],
            ),
          )
          as _i6.Future<List<_i16.ProductBalance>>);

  @override
  _i6.Future<List<_i14.ProductBrand>> getCachedProductBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductBrands, []),
            returnValue: _i6.Future<List<_i14.ProductBrand>>.value(
              <_i14.ProductBrand>[],
            ),
          )
          as _i6.Future<List<_i14.ProductBrand>>);

  @override
  _i6.Future<List<_i15.ProductSeries>> getCachedProductSeries({
    String? brandName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductSeries, [], {
              #brandName: brandName,
            }),
            returnValue: _i6.Future<List<_i15.ProductSeries>>.value(
              <_i15.ProductSeries>[],
            ),
          )
          as _i6.Future<List<_i15.ProductSeries>>);

  @override
  _i6.Future<List<_i18.ClientContract>> getCachedClientContracts({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedClientContracts, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i6.Future<List<_i18.ClientContract>>.value(
              <_i18.ClientContract>[],
            ),
          )
          as _i6.Future<List<_i18.ClientContract>>);

  @override
  _i6.Future<List<_i12.PromotionModel>> getCachedPromotions({
    bool? onlyActive = true,
    String? searchQuery,
    DateTime? dateFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPromotions, [], {
              #onlyActive: onlyActive,
              #searchQuery: searchQuery,
              #dateFilter: dateFilter,
            }),
            returnValue: _i6.Future<List<_i12.PromotionModel>>.value(
              <_i12.PromotionModel>[],
            ),
          )
          as _i6.Future<List<_i12.PromotionModel>>);

  @override
  _i6.Future<List<_i19.MainReport>> getCachedMainReports({String? userCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMainReports, [], {#userCode: userCode}),
            returnValue: _i6.Future<List<_i19.MainReport>>.value(
              <_i19.MainReport>[],
            ),
          )
          as _i6.Future<List<_i19.MainReport>>);

  @override
  _i6.Future<List<_i20.BusinessRegionReport>> getCachedBusinessRegionReports({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBusinessRegionReports, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i6.Future<List<_i20.BusinessRegionReport>>.value(
              <_i20.BusinessRegionReport>[],
            ),
          )
          as _i6.Future<List<_i20.BusinessRegionReport>>);

  @override
  _i6.Future<List<_i21.AKBByCategory>> getCachedAKBByCategories({
    int? mainReportId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAKBByCategories, [], {
              #mainReportId: mainReportId,
            }),
            returnValue: _i6.Future<List<_i21.AKBByCategory>>.value(
              <_i21.AKBByCategory>[],
            ),
          )
          as _i6.Future<List<_i21.AKBByCategory>>);

  @override
  _i6.Future<List<_i22.VisitPlan>> getCachedVisitPlans({
    int? mainReportId,
    String? clientCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVisitPlans, [], {
              #mainReportId: mainReportId,
              #clientCode: clientCode,
            }),
            returnValue: _i6.Future<List<_i22.VisitPlan>>.value(
              <_i22.VisitPlan>[],
            ),
          )
          as _i6.Future<List<_i22.VisitPlan>>);

  @override
  _i6.Future<List<_i23.VisitPlanList>> getCachedVisitPlanLists({
    int? visitPlanId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVisitPlanLists, [], {
              #visitPlanId: visitPlanId,
            }),
            returnValue: _i6.Future<List<_i23.VisitPlanList>>.value(
              <_i23.VisitPlanList>[],
            ),
          )
          as _i6.Future<List<_i23.VisitPlanList>>);

  @override
  _i6.Future<List<_i17.ProductWithPrice>> getCachedProductsWithPrices({
    required String? priceTypeCode,
    List<String>? warehouseCodes,
    String? searchQuery,
    String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductsWithPrices, [], {
              #priceTypeCode: priceTypeCode,
              #warehouseCodes: warehouseCodes,
              #searchQuery: searchQuery,
              #codeProject: codeProject,
            }),
            returnValue: _i6.Future<List<_i17.ProductWithPrice>>.value(
              <_i17.ProductWithPrice>[],
            ),
          )
          as _i6.Future<List<_i17.ProductWithPrice>>);

  @override
  _i6.Future<void> updateCachedClients(List<_i8.TradingPoint>? clients) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedClients, [clients]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resolveConflicts({
    required String? dataType,
    required List<Map<String, dynamic>>? localData,
    required List<Map<String, dynamic>>? remoteData,
    _i26.ConflictResolutionStrategy? strategy =
        _i26.ConflictResolutionStrategy.lastWriteWins,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolveConflicts, [], {
              #dataType: dataType,
              #localData: localData,
              #remoteData: remoteData,
              #strategy: strategy,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> retryFailedOperations() =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedOperations, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i28.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> saveUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [userData]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserByCredentials(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCredentials, [username, password]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByCode, [code]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> updateUser(String? code, Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [code, userData]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllUsersExcept(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllUsersExcept, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
