// Mocks generated by Mockito 5.4.6 from annotations
// in gloria_marketing_flutter/test/trading_points_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gloria_marketing_flutter/src/core/services/shared_preferences_service.dart'
    as _i3;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/business_region.dart'
    as _i12;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/client_contract.dart'
    as _i17;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/kpi_data.dart'
    as _i2;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/price_type.dart'
    as _i9;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_balance.dart'
    as _i14;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_brand.dart'
    as _i15;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_data.dart'
    as _i8;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_price.dart'
    as _i10;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_series.dart'
    as _i16;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/product_with_price.dart'
    as _i11;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/trading_point.dart'
    as _i7;
import 'package:gloria_marketing_flutter/src/features/agent/data/models/user_warehouse.dart'
    as _i13;
import 'package:gloria_marketing_flutter/src/features/agent/data/repositories/agent_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKpiData_0 extends _i1.SmartFake implements _i2.KpiData {
  _FakeKpiData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i3.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveCredentials(
    String? username,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [
              username,
              password,
              rememberMe,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserData({
    required String? userCode,
    required String? userName,
    required String? warehouseCode,
    required String? codeProject,
    required String? telegramID,
    required String? chatID,
    required String? topicID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userCode: userCode,
              #userName: userName,
              #warehouseCode: warehouseCode,
              #codeProject: codeProject,
              #telegramID: telegramID,
              #chatID: chatID,
              #topicID: topicID,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isRememberMeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isRememberMeEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> setServerName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setServerName, [name]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearServerName() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerName, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setBaseUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setBaseUrl, [url]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearBaseUrl() =>
      (super.noSuchMethod(
            Invocation.method(#clearBaseUrl, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setOfflineMode(bool? isOffline) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineMode, [isOffline]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#isOfflineMode, []),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> clearOfflineMode() =>
      (super.noSuchMethod(
            Invocation.method(#clearOfflineMode, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getLanguageCode() =>
      (super.noSuchMethod(
            Invocation.method(#getLanguageCode, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getLanguageCode, []),
            ),
          )
          as String);

  @override
  _i4.Future<void> clearLanguageCode() =>
      (super.noSuchMethod(
            Invocation.method(#clearLanguageCode, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setReportSentToTelegram(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setReportSentToTelegram, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isReportSentToTelegram() =>
      (super.noSuchMethod(
            Invocation.method(#isReportSentToTelegram, []),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [AgentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentRepository extends _i1.Mock implements _i6.AgentRepository {
  MockAgentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.KpiData> getKpiData({
    required String? userCode,
    required String? password,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKpiData, [], {
              #userCode: userCode,
              #password: password,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<_i2.KpiData>.value(
              _FakeKpiData_0(
                this,
                Invocation.method(#getKpiData, [], {
                  #userCode: userCode,
                  #password: password,
                  #forceRefresh: forceRefresh,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.KpiData>);

  @override
  _i4.Future<List<_i7.TradingPoint>> getClients({
    required String? userCode,
    required String? password,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClients, [], {
              #userCode: userCode,
              #password: password,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<List<_i7.TradingPoint>>.value(
              <_i7.TradingPoint>[],
            ),
          )
          as _i4.Future<List<_i7.TradingPoint>>);

  @override
  _i4.Future<List<_i8.ProductData>> getProducts({
    required String? codeProject,
    required String? codeSklad,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #codeProject: codeProject,
              #codeSklad: codeSklad,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<List<_i8.ProductData>>.value(
              <_i8.ProductData>[],
            ),
          )
          as _i4.Future<List<_i8.ProductData>>);

  @override
  _i4.Future<List<_i9.PriceType>> getPriceTypes({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPriceTypes, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<List<_i9.PriceType>>.value(
              <_i9.PriceType>[],
            ),
          )
          as _i4.Future<List<_i9.PriceType>>);

  @override
  _i4.Future<List<_i10.ProductPrice>> getProductPrices({
    required String? userCode,
    bool? forceRefresh = false,
    String? priceTypeCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductPrices, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
              #priceTypeCode: priceTypeCode,
            }),
            returnValue: _i4.Future<List<_i10.ProductPrice>>.value(
              <_i10.ProductPrice>[],
            ),
          )
          as _i4.Future<List<_i10.ProductPrice>>);

  @override
  _i4.Future<List<_i11.ProductWithPrice>> getProductsWithPrices({
    required String? priceTypeCode,
    List<String>? warehouseCodes,
    String? searchQuery,
    String? codeProject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsWithPrices, [], {
              #priceTypeCode: priceTypeCode,
              #warehouseCodes: warehouseCodes,
              #searchQuery: searchQuery,
              #codeProject: codeProject,
            }),
            returnValue: _i4.Future<List<_i11.ProductWithPrice>>.value(
              <_i11.ProductWithPrice>[],
            ),
          )
          as _i4.Future<List<_i11.ProductWithPrice>>);

  @override
  _i4.Future<void> updateClientVisitStatus(String? clientId, bool? isVisited) =>
      (super.noSuchMethod(
            Invocation.method(#updateClientVisitStatus, [clientId, isVisited]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncAllData({
    required String? userCode,
    required String? password,
    required String? codeProject,
    required String? codeSklad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllData, [], {
              #userCode: userCode,
              #password: password,
              #codeProject: codeProject,
              #codeSklad: codeSklad,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i12.BusinessRegion>> getCachedBusinessRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBusinessRegions, []),
            returnValue: _i4.Future<List<_i12.BusinessRegion>>.value(
              <_i12.BusinessRegion>[],
            ),
          )
          as _i4.Future<List<_i12.BusinessRegion>>);

  @override
  _i4.Future<List<_i12.BusinessRegion>> syncBusinessRegions({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncBusinessRegions, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<List<_i12.BusinessRegion>>.value(
              <_i12.BusinessRegion>[],
            ),
          )
          as _i4.Future<List<_i12.BusinessRegion>>);

  @override
  _i4.Future<List<_i13.UserWarehouse>> getCachedUserWarehouses() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUserWarehouses, []),
            returnValue: _i4.Future<List<_i13.UserWarehouse>>.value(
              <_i13.UserWarehouse>[],
            ),
          )
          as _i4.Future<List<_i13.UserWarehouse>>);

  @override
  _i4.Future<List<_i13.UserWarehouse>> syncUserWarehouses({
    required String? userCode,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncUserWarehouses, [], {
              #userCode: userCode,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<List<_i13.UserWarehouse>>.value(
              <_i13.UserWarehouse>[],
            ),
          )
          as _i4.Future<List<_i13.UserWarehouse>>);

  @override
  _i4.Future<void> savePrefsToUsers() =>
      (super.noSuchMethod(
            Invocation.method(#savePrefsToUsers, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i14.ProductBalance>> getCachedProductBalances({
    String? warehouseCode,
    String? productBrand,
    String? productSeries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductBalances, [], {
              #warehouseCode: warehouseCode,
              #productBrand: productBrand,
              #productSeries: productSeries,
            }),
            returnValue: _i4.Future<List<_i14.ProductBalance>>.value(
              <_i14.ProductBalance>[],
            ),
          )
          as _i4.Future<List<_i14.ProductBalance>>);

  @override
  _i4.Future<List<_i15.ProductBrand>> getCachedProductBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductBrands, []),
            returnValue: _i4.Future<List<_i15.ProductBrand>>.value(
              <_i15.ProductBrand>[],
            ),
          )
          as _i4.Future<List<_i15.ProductBrand>>);

  @override
  _i4.Future<List<_i16.ProductSeries>> getCachedProductSeries({
    String? brandName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductSeries, [], {
              #brandName: brandName,
            }),
            returnValue: _i4.Future<List<_i16.ProductSeries>>.value(
              <_i16.ProductSeries>[],
            ),
          )
          as _i4.Future<List<_i16.ProductSeries>>);

  @override
  _i4.Future<List<_i17.ClientContract>> getCachedClientContracts({
    String? clientCode,
    bool? active,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedClientContracts, [], {
              #clientCode: clientCode,
              #active: active,
            }),
            returnValue: _i4.Future<List<_i17.ClientContract>>.value(
              <_i17.ClientContract>[],
            ),
          )
          as _i4.Future<List<_i17.ClientContract>>);
}
