name: gloria_marketing_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Networking
  dio: ^5.4.0
  xml: ^6.5.0
  http: ^1.2.0

  # Database
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_storage: ^13.0.2

  # Maps & Permissions
  google_maps_flutter: ^2.6.0
#  yandex_mapkit: ^4.0.0
  yandex_maps_mapkit: ^4.25.0-beta # :contentReference[oaicite:6]{index=6}
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  permission_handler: ^12.0.1

  # Reactive Programming
  rxdart: ^0.28.0

  # Service Locator
  get_it: ^8.0.3

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1

  # URL Launcher
  url_launcher: ^6.2.4

  # Utilities
  archive: ^4.0.7

  # Background tasks
  workmanager: ^0.9.0

  # UI enhancements
  shimmer: ^3.0.0

  # Connectivity
  connectivity_plus: ^7.0.0

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  geolocator: ^14.0.2
  flutter_polyline_points: ^2.0.0
  camera: ^0.11.3
  image_picker: ^1.2.0
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  open_file: ^3.5.10
  device_info_plus: ^12.3.0
  battery_plus: ^6.0.3
  file_picker: ^10.3.7

  # PDF Generation & Sharing
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

  # Database testing
  sqflite_common_ffi: ^2.3.3

  # Mocking
  mockito: ^5.4.4
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Generate localization files
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/db/
    - assets/images/marker.png
    - assets/images/marker_user.png
    - assets/images/pruduct/
    - assets/fonts/
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon/selup_icon.png
    background_color: "#FFFFFF"
    theme_color: "#3B82F6"
  macos:
    generate: true
    image_path: assets/icon/selup_icon.png
  windows:
    generate: true
    image_path: assets/icon/selup_icon.png
  linux:
    generate: true
    image_path: assets/icon/selup_icon.png

  image_path: assets/icon/selup_icon.png
  adaptive_icon_background: "#FFFFFF"   # Android adaptiv fon
  adaptive_icon_foreground: assets/icon/selup_icon.png
  adaptive_icon_monochrome: assets/icon/selup_icon.png