// File generated manually from the Firebase project `selup-c49e1`.
// Mirrors the layout produced by `flutterfire configure` so it can be
// regenerated by the CLI later without code churn.
//
// Reference:
//   * Android: android/app/google-services.json
//   * iOS    : ios/Runner/GoogleService-Info.plist
//
// Keep the three files in sync — when Firebase Console rotates an API
// key, update all three at once.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not configured for web — '
        're-run `flutterfire configure` if web support is added.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform — Phase 1 ships Android + iOS only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJG9J6fwGcLIG5hkwUtTS2Omc6m_-lop8',
    appId: '1:722694864687:android:2f3497d90df42ab2346bda',
    messagingSenderId: '722694864687',
    projectId: 'selup-c49e1',
    storageBucket: 'selup-c49e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg6EPyG6df8gQ8ko9z2WvTK98R4bN20kA',
    appId: '1:722694864687:ios:a71af8a7b61fbef6346bda',
    messagingSenderId: '722694864687',
    projectId: 'selup-c49e1',
    storageBucket: 'selup-c49e1.firebasestorage.app',
    iosBundleId: 'com.maxsoft.selup',
  );
}
